o/addbytes.a: addbytes.c
  compile +e +w -i addbytes.c CC=(-D_CURSES_PRIVATE) keep=o/addbytes

o/addch.a: addch.c
  compile +e +w -i addch.c CC=(-D_CURSES_PRIVATE) keep=o/addch

o/addstr.a: addstr.c
  compile +e +w -i addstr.c CC=(-D_CURSES_PRIVATE) keep=o/addstr

o/box.a: box.c
  compile +e +w -i box.c CC=(-D_CURSES_PRIVATE) keep=o/box

o/clear.a: clear.c
  compile +e +w -i clear.c CC=(-D_CURSES_PRIVATE) keep=o/clear

o/clrtobot.a: clrtobot.c
  compile +e +w -i clrtobot.c CC=(-D_CURSES_PRIVATE) keep=o/clrtobot

o/clrtoeol.a: clrtoeol.c
  compile +e +w -i clrtoeol.c CC=(-D_CURSES_PRIVATE) keep=o/clrtoeol

o/cr.put.a: cr.put.c
  compile +e +w -i cr.put.c CC=(-D_CURSES_PRIVATE) keep=o/cr.put

o/curses.a: curses.c
  compile +e +w -i curses.c CC=(-D_CURSES_PRIVATE) keep=o/curses

o/delch.a: delch.c
  compile +e +w -i delch.c CC=(-D_CURSES_PRIVATE) keep=o/delch

o/deleteln.a: deleteln.c
  compile +e +w -i deleteln.c CC=(-D_CURSES_PRIVATE) keep=o/deleteln

o/delwin.a: delwin.c
  compile +e +w -i delwin.c CC=(-D_CURSES_PRIVATE) keep=o/delwin

o/erase.a: erase.c
  compile +e +w -i erase.c CC=(-D_CURSES_PRIVATE) keep=o/erase

o/fullname.a: fullname.c
  compile +e +w -i fullname.c CC=(-D_CURSES_PRIVATE) keep=o/fullname

o/getch.a: getch.c
  compile +e +w -i getch.c CC=(-D_CURSES_PRIVATE) keep=o/getch

o/getstr.a: getstr.c
  compile +e +w -i getstr.c CC=(-D_CURSES_PRIVATE) keep=o/getstr

o/id.subwins.a: id.subwins.c
  compile +e +w -i id.subwins.c CC=(-D_CURSES_PRIVATE) keep=o/id.subwins

o/idlok.a: idlok.c
  compile +e +w -i idlok.c CC=(-D_CURSES_PRIVATE) keep=o/idlok

o/initscr.a: initscr.c
  compile +e +w -i initscr.c CC=(-D_CURSES_PRIVATE) keep=o/initscr

o/insch.a: insch.c
  compile +e +w -i insch.c CC=(-D_CURSES_PRIVATE) keep=o/insch

o/insertln.a: insertln.c
  compile +e +w -i insertln.c CC=(-D_CURSES_PRIVATE) keep=o/insertln

o/longname.a: longname.c
  compile +e +w -i longname.c CC=(-D_CURSES_PRIVATE) keep=o/longname

o/move.a: move.c
  compile +e +w -i move.c CC=(-D_CURSES_PRIVATE) keep=o/move

o/mvwin.a: mvwin.c
  compile +e +w -i mvwin.c CC=(-D_CURSES_PRIVATE) keep=o/mvwin

o/newwin.a: newwin.c
  compile +e +w -i newwin.c CC=(-D_CURSES_PRIVATE) keep=o/newwin

o/overlay.a: overlay.c
  compile +e +w -i overlay.c CC=(-D_CURSES_PRIVATE) keep=o/overlay

o/overwrite.a: overwrite.c
  compile +e +w -i overwrite.c CC=(-D_CURSES_PRIVATE) keep=o/overwrite

o/printw.a: printw.c
  compile +e +w -i printw.c CC=(-D_CURSES_PRIVATE) keep=o/printw

o/putchar.a: putchar.c
  compile +e +w -i putchar.c CC=(-D_CURSES_PRIVATE) keep=o/putchar

o/refresh.a: refresh.c
  compile +e +w -i refresh.c CC=(-D_CURSES_PRIVATE) keep=o/refresh

o/scanw.a: scanw.c
  compile +e +w -i scanw.c CC=(-D_CURSES_PRIVATE) keep=o/scanw

o/scroll.a: scroll.c
  compile +e +w -i scroll.c CC=(-D_CURSES_PRIVATE) keep=o/scroll

o/setterm.a: setterm.c
  compile +e +w -i setterm.c CC=(-D_CURSES_PRIVATE) keep=o/setterm

o/standout.a: standout.c
  compile +e +w -i standout.c CC=(-D_CURSES_PRIVATE) keep=o/standout

o/toucholap.a: toucholap.c
  compile +e +w -i toucholap.c CC=(-D_CURSES_PRIVATE) keep=o/toucholap

o/touchwin.a: touchwin.c
  compile +e +w -i touchwin.c CC=(-D_CURSES_PRIVATE) keep=o/touchwin

o/trace.a: trace.c
  compile +e +w -i trace.c CC=(-D_CURSES_PRIVATE) keep=o/trace

o/tstp.a: tstp.c
  compile +e +w -i tstp.c CC=(-D_CURSES_PRIVATE) keep=o/tstp

o/tty.a: tty.c
  compile +e +w -i tty.c CC=(-D_CURSES_PRIVATE) keep=o/tty

o/unctrl.a: unctrl.c
  compile +e +w -i unctrl.c CC=(-D_CURSES_PRIVATE) keep=o/unctrl
