Dear GNO Enthusiasts,

  This is one of the neatest programs I've seen in a while. The README
file describes it well.

  All the ".flf" files should go in a directory /usr/games/lib/figlet.dir;
just run the script 'install.gno', which takes care of this and other such
stuff for you.

  BTW, figlet compiled under GNO/ME with no modifications at all to the
source code.  Portable programming such as this will allow GNO/ME to gain
more software, trivially, over time.

  Enjoy!

Jawaid
