/* A lexical scanner generated by flex */

/* scanner skeleton version:
 * $Header: /usr/fsys/odin/a/vern/flex/RCS/flex.skel,v 2.16 90/08/03 14:09:36 vern Exp $
 */

#define FLEX_SCANNER

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <osfcn.h>

/* use prototypes in function declarations */
#define YY_USE_PROTOS

/* the "const" storage-class-modifier is valid */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#ifdef __STDC__

#ifdef __GNUC__
#include <stddef.h>
void *malloc( size_t );
void free( void* );
#else
#include <stdlib.h>
#endif	/* __GNUC__ */

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */


#ifdef __TURBOC__
#define YY_USE_CONST
#endif


#ifndef YY_USE_CONST
#define const
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
/* we can't get here if it's an ANSI C compiler, or a C++ compiler,
 * so it's got to be a K&R compiler, and therefore there's no standard
 * place from which to include these definitions
 */
char *malloc();
int free();
int read();
#endif


/* amount of stuff to slurp up with each read */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* returned upon end-of-file */
#define YY_END_TOK 0

/* copy whatever the last rule matched to the standard output */

/* cast to (char *) is because for 8-bit chars, yytext is (unsigned char *) */
/* this used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite()
 */
#define ECHO (void) fwrite( (char *) yytext, yyleng, 1, yyout )

/* gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#define YY_INPUT(buf,result,max_size) \
	if ( (result = read( fileno(yyin), (char *) buf, max_size )) < 0 ) \
	    YY_FATAL_ERROR( "read() in flex scanner failed" );
#define YY_NULL 0

/* no semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#define yyterminate() return ( YY_NULL )

/* report a fatal error */

/* The funky do-while is used to turn this macro definition into
 * a single C statement (which needs a semi-colon terminator).
 * This avoids problems with code like:
 *
 * 	if ( something_happens )
 *		YY_FATAL_ERROR( "oops, the something happened" );
 *	else
 *		everything_okay();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the YY_FATAL_ERROR() call.
 */

#define YY_FATAL_ERROR(msg) \
	do \
		{ \
		(void) fputs( msg, stderr ); \
		(void) putc( '\n', stderr ); \
		exit( 1 ); \
		} \
	while ( 0 )

/* default yywrap function - always treat EOF as an EOF */
#define yywrap() 1

/* enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN
 */
#define BEGIN yy_start = 1 + 2 *

/* action number for EOF rule of a given start state */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* special action meaning "start processing a new file" */
#define YY_NEW_FILE \
	do \
		{ \
		yy_init_buffer( yy_current_buffer, yyin ); \
		yy_load_buffer_state(); \
		} \
	while ( 0 )

/* default declaration of generated scanner - a define so the user can
 * easily add parameters
 */
#define YY_DECL int yylex YY_PROTO(( void )) 

/* code executed at the end of each rule */
#define YY_BREAK break;

#define YY_END_OF_BUFFER_CHAR 0

#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE (YY_READ_BUF_SIZE * 2) /* size of default input buffer */
#endif

typedef struct yy_buffer_state *YY_BUFFER_STATE;

#define YY_CHAR char
# line 1 "jive.l"
#define INITIAL 0
# line 11 "jive.l"
	char buf[128];

# line 15 "jive.l"

/* done after the current pattern has been matched and before the
 * corresponding action - sets up yytext
 */
#define YY_DO_BEFORE_ACTION \
	yytext = yy_bp; \
	yyleng = yy_cp - yy_bp; \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* return all but the first 'n' matched characters back to the input stream */
#define yyless(n) \
	do \
		{ \
		/* undo effects of setting up yytext */ \
		*yy_cp = yy_hold_char; \
		yy_c_buf_p = yy_cp = yy_bp + n; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext )


struct yy_buffer_state
    {
    FILE *yy_input_file;

    YY_CHAR *yy_ch_buf;		/* input buffer */
    YY_CHAR *yy_buf_pos;	/* current position in input buffer */

    /* size of input buffer in bytes, not including room for EOB characters*/
    int yy_buf_size;	

    /* number of characters read into yy_ch_buf, not including EOB characters */
    int yy_n_chars;

    int yy_eof_status;		/* whether we've seen an EOF on this buffer */
#define EOF_NOT_SEEN 0
    /* "pending" happens when the EOF has been seen but there's still
     * some text process
     */
#define EOF_PENDING 1
#define EOF_DONE 2
    };

static YY_BUFFER_STATE yy_current_buffer;

/* we provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state"
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed */
static YY_CHAR yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */



#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

#ifndef YY_USER_INIT
#define YY_USER_INIT
#endif

extern YY_CHAR *yytext;
extern int yyleng;
extern FILE *yyin, *yyout;

YY_CHAR *yytext;
int yyleng;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

#define YY_END_OF_BUFFER 210
typedef int yy_state_type;
static const short int yy_accept[777] =
    {   0,
        0,    0,  210,  206,  207,  206,  206,   55,  206,  206,
      206,  206,  206,  206,  206,  206,  206,  206,  206,  206,
      206,  206,  206,  206,  206,  206,  206,  206,  206,  206,
      206,  206,  206,  206,  206,  206,  206,  206,  206,  206,
      206,  206,  206,  206,  206,  206,  206,  206,  206,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,  204,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   94,    0,    0,
        0,    0,    0,   28,  167,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   29,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   30,    0,    0,    0,    0,
        0,    0,    0,    0,   31,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   71,    0,    0,    0,    0,   32,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   93,
        0,   33,    0,  201,    0,    0,    0,    0,    0,    0,
       34,    0,    0,    0,    0,    0,    0,    0,    0,    0,
      178,    0,    0,    0,    0,    0,   96,    0,    0,    0,
        0,    0,    0,    0,  113,    0,    0,    0,    0,    0,

        0,    0,    0,  177,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   26,    0,    0,    0,
        0,    0,    0,  150,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,  205,    0,   87,    0,    0,    0,
        0,    0,  160,    0,  193,    0,    0,    0,  192,    0,
        0,    0,    0,   56,    0,    0,    0,    0,    0,  115,
        0,    0,    0,    0,    0,  106,  110,  111,    0,    0,
        0,    0,    0,    0,    0,   83,    0,    0,    0,    0,
        0,   95,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,  129,    0,    0,    0,    0,  127,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,  173,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   86,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,  130,    0,    0,    0,  112,
        0,   37,   52,    0,    0,  196,    0,    0,    0,    0,
        0,  170,    0,    0,    0,  161,    0,    0,   97,    0,
        0,   27,    0,    0,   41,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   35,    6,  191,    0,   81,

        0,    0,    0,    0,    0,    0,    0,    0,  109,    0,
      198,  163,    0,    0,    0,    0,    0,    0,  122,    0,
      172,    0,  202,    0,    0,    1,    0,   15,    0,   82,
        0,   23,  123,    0,    0,  180,   51,  162,   67,    0,
        0,    0,   14,    0,    0,    0,   77,    0,  114,    0,
      179,    0,    0,    0,    0,    0,   68,   64,  105,    0,
        0,    0,  128,    0,    0,    0,  154,    0,    0,    0,
        0,    0,    0,    2,    0,    0,    0,    0,   36,    0,
       12,  181,   98,    0,    5,  108,    0,  190,    0,  171,
        0,  164,    0,    0,    0,    0,    0,    0,   80,  137,

      136,  147,    0,  148,  143,    0,    0,    0,    0,    0,
        0,   57,    0,   59,  100,   47,    0,   25,   21,  118,
        0,    0,    0,   69,   91,   48,    0,    0,  126,  174,
        0,  145,    0,    0,  142,    0,  149,    0,    0,    0,
        0,  141,    0,    0,    0,    0,    0,    0,    0,    4,
        0,    0,  203,    0,    0,    0,    0,    0,    0,   13,
       58,    0,   88,    0,    0,    0,    0,    0,    0,    0,
        0,    0,  131,    0,    0,  107,    0,    0,   16,    0,
      166,  182,  124,    0,  200,    0,    0,    0,    0,    0,
        0,    0,    0,  169,    0,  194,    0,    0,    0,    0,

        7,    0,    0,    0,  197,    0,   62,   39,   22,  117,
       92,    0,   85,  139,  138,    0,    0,    0,    0,   60,
       54,  159,  119,   61,    0,    0,   66,    0,    0,    0,
      151,    0,  144,  140,  146,  103,   18,    0,   42,    0,
        0,   84,  183,    0,  156,    0,    0,   20,  158,    0,
       17,    0,  185,   40,    0,    0,    0,    0,   43,    0,
       72,    0,    0,    0,    0,    0,  165,   65,   89,    0,
      155,    0,    0,    0,  186,    0,    0,    0,   19,    0,
        0,    0,    0,    0,  102,    0,    0,    0,    0,   63,
       90,   79,    0,   10,    8,  104,  168,   44,   78,    0,

        0,  132,    0,    0,   50,   49,   75,   11,  116,    0,
        9,    0,  125,  153,    0,    0,    3,    0,  195,    0,
        0,  188,    0,    0,    0,   99,   46,    0,  134,    0,
        0,   70,  184,    0,  199,  152,    0,    0,    0,  157,
        0,  189,    0,    0,   45,  101,    0,   53,    0,   73,
        0,   24,    0,    0,   38,    0,   76,    0,  176,    0,
        0,    0,    0,    0,  135,    0,    0,    0,    0,  175,
        0,   74,    0,    0,  133,    0
    } ;

static const YY_CHAR yy_ec[128] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    3,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    1,    1,    1,    1,    1,    6,    1,
        1,    1,    1,    1,    7,    8,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    9,    1,    1,
        1,    1,    1,    1,   10,   11,    1,   12,    1,    1,
        1,   13,   14,   15,    1,   16,   17,   18,    1,   19,
        1,   20,   21,   22,   23,   24,   25,   26,   27,    1,
        1,    1,    1,    1,    1,    1,   28,   29,   30,   31,

       32,   33,   34,   35,   36,   37,   38,   39,   40,   41,
       42,   43,   44,   45,   46,   47,   48,   49,   50,   51,
       52,   53,    1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[54] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1
    } ;

static const short int yy_base[777] =
    {   0,
        0,    0,  849,  850,  850,  850,   50,  850,  806,  815,
      818,  809,   62,  802,  815,  810,   26,   27,  806,  822,
      829,  806,  795,  106,  146,   62,   97,   68,   99,   85,
       96,  122,  114,  107,  131,  157,  162,  164,  151,   48,
      172,  206,  197,  167,   51,  207,  827,  178,   54,  251,
      793,  830,   45,  805,   83,  173,  185,   46,   98,  787,
      799,   70,  157,  794,  198,  100,  796,  129,  796,  209,
      186,  795,  794,   95,  795,  775,  850,  795,  791,  793,
      225,  775,  768,  790,  143,  776,  771,  850,  801,  788,
      774,  764,  764,  850,  850,  765,  130,  777,  770,  768,

      191,  167,  772,  177,  199,  753,  764,  756,  217,  212,
      771,  232,  765,  753,  850,  795,   74,  222,  220,  762,
      752,  223,  227,  768,  755,  850,  253,  790,  765,  743,
      745,  172,  246,  752,  850,  755,  242,  260,  742,  747,
      756,  740,  756,  751,  850,  739,  232,  261,  271,  850,
      750,  745,  738,  750,  265,  732,  731,  728,  270,  850,
      732,  850,  275,  850,  271,  275,  287,  236,  733,  736,
      850,  723,  312,  287,  292,  742,  741,  740,  289,  738,
      850,  736,  725,  719,  715,  726,  757,  720,  727,  292,
      730,  284,  717,  709,  725,  712,  706,  281,  704,  747,

      718,  292,  708,  850,  714,  713,  742,  291,  717,  702,
      739,  697,  705,  736,  694,  693,  850,  730,  708,  699,
      694,  697,  693,  850,  690,  698,  684,  692,  693,  694,
      697,  693,  691,  696,  850,  682,  324,  685,  683,  677,
      670,  331,  850,  688,  850,  677,  667,  685,  850,  674,
      665,  682,  671,  850,  300,  673,  677,  675,  660,  850,
      658,  697,  661,  652,  665,  850,  850,  850,  667,  652,
      301,  652,  664,  656,  663,  689,  660,  646,  658,  658,
      656,  850,  639,  645,  646,  652,  636,  643,  650,  630,
      629,  646,  649,  648,  639,  642,  645,  640,  635,  638,

      637,  850,  616,  626,  634,  622,  201,  628,  616,  630,
      612,  614,  619,  624,  621,  614,  624,  615,  621,  605,
      623,  618,  614,  616,  609,  605,  613,  593,  596,  850,
      610,  602,  593,  592,  591,  605,  597,  313,  588,  336,
      604,  588,  585,  584,  626,  591,  624,  306,  588,  587,
      583,  620,  595,  586,  591,  850,  616,  587,  614,  850,
      577,  850,  850,  612,  569,  850,  610,  609,  342,  567,
      577,  850,  575,  578,  576,  850,  571,  565,  601,  552,
      571,  850,  554,  570,  850,  572,  563,  594,  554,  544,
      565,  566,  548,  553,  539,  850,  850,  850,  545,  850,

      557,  554,  545,  554,  544,  578,  537,  550,  850,  533,
      850,  850,  542,  547,  574,  529,  544,  543,  850,  532,
      850,  526,  850,  540,  539,  850,  523,  850,  540,  850,
      527,  850,  850,  520,  521,  850,  343,  850,  850,  520,
      522,  527,  850,  558,  529,  556,  850,  518,  850,  505,
      850,  527,  516,  515,  502,  523,  850,  850,  850,  346,
      507,  512,  850,  508,  519,  512,  850,  516,  510,  513,
      499,  501,  500,  850,  502,  493,  535,  497,  850,  505,
      490,  850,  850,  490,  850,  345,  489,  850,  501,  850,
      500,  850,  527,  489,  488,  496,  482,  492,  850,  850,

      850,  850,  521,  850,  850,  520,  477,  470,  473,  488,
      481,  514,  513,  512,  850,  511,  482,  850,  850,  850,
      509,  470,  479,  850,  850,  850,  469,  475,  850,  850,
      462,  850,  466,  478,  850,  470,  850,  476,  462,  455,
      470,  850,  468,  495,  463,  450,  448,  453,  447,  850,
      446,  446,  850,  450,  448,  442,  484,  483,  450,  850,
      850,  481,  850,  456,  452,  440,  440,  433,  473,  446,
      430,  448,  850,  444,  432,  850,  437,  444,  850,  431,
      850,  850,  850,  439,  850,  437,  427,  435,  433,  437,
      433,  459,  434,  850,  422,  850,  425,  417,  424,  453,

      850,  410,  408,  450,  850,  408,  850,  417,  850,  850,
      850,  419,  850,  850,  850,  403,  407,  402,  398,  850,
      442,  850,  850,  850,  400,  410,  850,  411,  414,  400,
      850,  399,  850,  850,  850,  850,  850,  392,  850,  393,
      390,  850,  850,  404,  850,  386,  402,  850,  850,  386,
      850,  393,  850,  850,  391,  388,  382,  397,  850,  386,
      850,  393,  384,  383,  391,  418,  850,  850,  850,  388,
      850,  388,  379,  378,  850,  381,  383,  383,  850,  367,
      371,  365,  370,  382,  850,  405,  360,  375,  374,  850,
      850,  850,  362,  850,  850,  850,  850,  850,  850,  372,

      358,  850,  363,  369,  850,  850,  850,  850,  850,  368,
      850,  368,  850,  850,  357,  361,  850,  355,  850,  391,
      366,  850,  351,  388,  341,  385,  342,  382,  850,  343,
      338,  850,  850,  341,  850,  850,  333,  338,  342,  850,
      334,  850,  342,  341,  850,  367,  331,  850,  321,  850,
      331,  850,  335,  326,  850,  328,  850,  317,  358,  329,
      314,  312,  321,  326,  850,  323,  307,  306,  307,  850,
      200,  850,  111,   40,  850,  850
    } ;

static const short int yy_def[777] =
    {   0,
      776,    1,  776,  776,  776,  776,  776,  776,  776,  776,
      776,  776,  776,  776,  776,  776,  776,  776,  776,  776,
      776,  776,  776,  776,  776,  776,  776,  776,  776,  776,
      776,  776,  776,  776,  776,  776,  776,  776,  776,  776,
      776,  776,  776,  776,  776,  776,  776,  776,  776,  776,
      776,  776,  776,  776,  776,  776,  776,  776,  776,  776,
      776,  776,  776,  776,  776,  776,  776,  776,  776,  776,
      776,  776,  776,  776,  776,  776,  776,  776,  776,  776,
      776,  776,  776,  776,  776,  776,  776,  776,  776,  776,
      776,  776,  776,  776,  776,  776,  776,  776,  776,  776,

      776,  776,  776,  776,  776,  776,  776,  776,  776,  776,
      776,  776,  776,  776,  776,  776,  776,  776,  776,  776,
      776,  776,  776,  776,  776,  776,  776,  776,  776,  776,
      776,  776,  776,  776,  776,  776,  776,  776,  776,  776,
      776,  776,  776,  776,  776,  776,  776,  776,  776,  776,
      776,  776,  776,  776,  776,  776,  776,  776,  776,  776,
      776,  776,  776,  776,  776,  776,  776,  776,  776,  776,
      776,  776,  776,  776,  776,  776,  776,  776,  776,  776,
      776,  776,  776,  776,  776,  776,  776,  776,  776,  776,
      776,  776,  776,  776,  776,  776,  776,  776,  776,  776,

      776,  776,  776,  776,  776,  776,  776,  776,  776,  776,
      776,  776,  776,  776,  776,  776,  776,  776,  776,  776,
      776,  776,  776,  776,  776,  776,  776,  776,  776,  776,
      776,  776,  776,  776,  776,  776,  776,  776,  776,  776,
      776,  776,  776,  776,  776,  776,  776,  776,  776,  776,
      776,  776,  776,  776,  776,  776,  776,  776,  776,  776,
      776,  776,  776,  776,  776,  776,  776,  776,  776,  776,
      776,  776,  776,  776,  776,  776,  776,  776,  776,  776,
      776,  776,  776,  776,  776,  776,  776,  776,  776,  776,
      776,  776,  776,  776,  776,  776,  776,  776,  776,  776,

      776,  776,  776,  776,  776,  776,  776,  776,  776,  776,
      776,  776,  776,  776,  776,  776,  776,  776,  776,  776,
      776,  776,  776,  776,  776,  776,  776,  776,  776,  776,
      776,  776,  776,  776,  776,  776,  776,  776,  776,  776,
      776,  776,  776,  776,  776,  776,  776,  776,  776,  776,
      776,  776,  776,  776,  776,  776,  776,  776,  776,  776,
      776,  776,  776,  776,  776,  776,  776,  776,  776,  776,
      776,  776,  776,  776,  776,  776,  776,  776,  776,  776,
      776,  776,  776,  776,  776,  776,  776,  776,  776,  776,
      776,  776,  776,  776,  776,  776,  776,  776,  776,  776,

      776,  776,  776,  776,  776,  776,  776,  776,  776,  776,
      776,  776,  776,  776,  776,  776,  776,  776,  776,  776,
      776,  776,  776,  776,  776,  776,  776,  776,  776,  776,
      776,  776,  776,  776,  776,  776,  776,  776,  776,  776,
      776,  776,  776,  776,  776,  776,  776,  776,  776,  776,
      776,  776,  776,  776,  776,  776,  776,  776,  776,  776,
      776,  776,  776,  776,  776,  776,  776,  776,  776,  776,
      776,  776,  776,  776,  776,  776,  776,  776,  776,  776,
      776,  776,  776,  776,  776,  776,  776,  776,  776,  776,
      776,  776,  776,  776,  776,  776,  776,  776,  776,  776,

      776,  776,  776,  776,  776,  776,  776,  776,  776,  776,
      776,  776,  776,  776,  776,  776,  776,  776,  776,  776,
      776,  776,  776,  776,  776,  776,  776,  776,  776,  776,
      776,  776,  776,  776,  776,  776,  776,  776,  776,  776,
      776,  776,  776,  776,  776,  776,  776,  776,  776,  776,
      776,  776,  776,  776,  776,  776,  776,  776,  776,  776,
      776,  776,  776,  776,  776,  776,  776,  776,  776,  776,
      776,  776,  776,  776,  776,  776,  776,  776,  776,  776,
      776,  776,  776,  776,  776,  776,  776,  776,  776,  776,
      776,  776,  776,  776,  776,  776,  776,  776,  776,  776,

      776,  776,  776,  776,  776,  776,  776,  776,  776,  776,
      776,  776,  776,  776,  776,  776,  776,  776,  776,  776,
      776,  776,  776,  776,  776,  776,  776,  776,  776,  776,
      776,  776,  776,  776,  776,  776,  776,  776,  776,  776,
      776,  776,  776,  776,  776,  776,  776,  776,  776,  776,
      776,  776,  776,  776,  776,  776,  776,  776,  776,  776,
      776,  776,  776,  776,  776,  776,  776,  776,  776,  776,
      776,  776,  776,  776,  776,  776,  776,  776,  776,  776,
      776,  776,  776,  776,  776,  776,  776,  776,  776,  776,
      776,  776,  776,  776,  776,  776,  776,  776,  776,  776,

      776,  776,  776,  776,  776,  776,  776,  776,  776,  776,
      776,  776,  776,  776,  776,  776,  776,  776,  776,  776,
      776,  776,  776,  776,  776,  776,  776,  776,  776,  776,
      776,  776,  776,  776,  776,  776,  776,  776,  776,  776,
      776,  776,  776,  776,  776,  776,  776,  776,  776,  776,
      776,  776,  776,  776,  776,  776,  776,  776,  776,  776,
      776,  776,  776,  776,  776,  776,  776,  776,  776,  776,
      776,  776,  776,  776,  776,    0
    } ;

static const short int yy_nxt[904] =
    {   0,
        4,    5,    6,    7,    8,    4,    9,    4,    4,    4,
       10,   11,   12,   13,   14,   15,   16,    4,    4,   17,
       18,   19,   20,   21,   22,    4,   23,   24,   25,   26,
       27,   28,   29,   30,   31,   32,   33,   34,   35,   36,
       37,   38,   39,   40,   41,   42,   43,   44,   45,   46,
       47,   48,   49,   50,   86,  150,   95,   84,  162,   95,
       51,  171,   95,   52,   53,   78,   54,   85,   55,  775,
       95,  114,  182,  192,   87,  115,   95,   56,   57,   58,
      183,   59,   60,   61,   62,   63,   53,  193,   64,   65,
       66,   67,   68,   95,   69,   70,   71,  198,   72,   73,

      108,  217,   79,  107,   95,   95,  115,   95,   80,   93,
      185,  199,  116,   94,   95,   95,  267,  186,  117,  268,
      121,  126,   95,  123,  109,  194,  122,  124,  110,  126,
       95,  205,  111,  240,  118,  206,  218,  125,  112,   95,
      119,  113,  132,  120,   96,   97,  774,  133,  195,  130,
       98,   99,  100,   94,   95,   81,  208,  241,   82,   95,
      181,  131,  127,  186,  135,   95,  134,  128,  129,  135,
       95,  230,   95,  101,  162,   95,  187,  102,  146,  150,
       95,  103,  147,  231,  136,  171,   95,  104,  137,  140,
      105,  142,  148,  106,  247,  149,  248,  141,  138,  151,

      158,  143,  200,   84,  139,   95,  144,  163,  145,  164,
      288,  188,  289,   85,   95,   95,  190,  189,  250,  172,
      213,  245,  251,  191,  159,  202,  180,  214,  463,  203,
      252,  160,  161,   86,  165,  152,  246,  153,  166,  258,
      253,  167,  168,  210,  773,  154,  464,  155,  169,  204,
      211,  170,  156,  157,   50,  212,  224,  257,  259,  225,
      269,  271,  278,  261,  275,  220,  270,  272,  336,  276,
      226,  277,  262,  306,  337,  279,  307,  290,  173,  174,
      175,  263,  176,  222,   61,  177,  282,  291,  294,  283,
      296,   66,  295,  178,  297,   69,  179,   71,  311,  308,

      298,  309,  312,  310,  319,  327,  313,  324,  325,  320,
      328,  329,  314,  332,  334,  187,  330,  331,  341,  342,
      333,  353,  335,  210,  356,  191,  363,  364,  357,  399,
      354,  415,  368,  193,  405,  212,  348,  373,  349,  428,
      494,  497,  416,  503,  495,  520,  568,  429,  603,  583,
      188,  772,  771,  770,  769,  768,  767,  504,  766,  765,
      764,  763,  762,  761,  760,  759,  758,  757,  400,  756,
      746,  406,  755,  754,  753,  752,  498,  584,  751,  750,
      499,  749,  748,  569,  747,  746,  745,  521,  726,  744,
      604,  743,  742,  741,  740,  739,  738,  737,  736,  735,

      734,  733,  732,  731,  730,  729,  728,  727,  726,  725,
      724,  723,  722,  721,  720,  719,  718,  717,  716,  715,
      714,  713,  712,  711,  710,  709,  708,  707,  706,  705,
      704,  703,  702,  701,  700,  699,  698,  697,  696,  695,
      694,  693,  692,  691,  690,  621,  689,  688,  687,  686,
      685,  684,  683,  682,  681,  680,  679,  678,  677,  676,
      675,  674,  673,  672,  671,  670,  669,  668,  667,  666,
      665,  664,  663,  662,  661,  660,  659,  658,  657,  656,
      655,  654,  653,  652,  651,  650,  649,  648,  647,  646,
      645,  644,  643,  642,  641,  640,  639,  638,  637,  636,

      635,  634,  633,  632,  631,  630,  629,  628,  627,  626,
      625,  624,  623,  622,  516,  514,  621,  512,  620,  619,
      618,  617,  616,  615,  614,  613,  612,  611,  610,  609,
      608,  607,  606,  605,  602,  601,  600,  599,  598,  597,
      596,  595,  594,  593,  592,  591,  590,  589,  588,  587,
      586,  585,  582,  581,  580,  579,  578,  577,  576,  575,
      574,  573,  572,  571,  570,  567,  566,  565,  564,  563,
      562,  561,  560,  559,  558,  557,  556,  555,  554,  553,
      552,  551,  550,  549,  548,  547,  546,  545,  544,  543,
      542,  541,  540,  539,  538,  537,  536,  535,  534,  533,

      532,  531,  530,  529,  379,  528,  527,  526,  525,  524,
      523,  522,  519,  518,  517,  516,  515,  514,  513,  512,
      511,  510,  509,  508,  507,  506,  505,  502,  501,  500,
      373,  364,  357,  353,  496,  493,  492,  491,  490,  489,
      488,  487,  486,  485,  484,  483,  482,  481,  480,  479,
      478,  477,  476,  475,  474,  473,  472,  471,  470,  469,
      468,  467,  466,  465,  462,  461,  460,  459,  458,  457,
      456,  455,  454,  453,  452,  451,  450,  449,  448,  447,
      446,  445,  444,  443,  442,  441,  440,  439,  438,  437,
      436,  435,  434,  433,  432,  431,  430,  427,  426,  425,

      424,  423,  422,  421,  420,  419,  418,  417,  414,  413,
      412,  411,  410,  409,  408,  407,  404,  403,  402,  401,
      398,  397,  396,  395,  394,  393,  392,  391,  390,  389,
      388,  387,  386,  385,  384,  383,  382,  381,  380,  379,
      378,  377,  376,  375,  374,  372,  371,  370,  369,  367,
      366,  365,  362,  361,  360,  359,  358,  355,  352,  351,
      187,  350,  349,  348,  347,  346,  345,  344,  343,  194,
      340,  339,  338,  326,  323,  322,  321,  318,  317,  316,
      315,  305,  304,  303,  302,  301,  300,  299,  293,  292,
      287,  286,  285,  284,  281,  280,  274,  273,  266,  265,

      264,  260,  256,  255,  254,  249,  244,  243,  242,  239,
      238,  237,  236,  235,  234,  233,  232,  229,  228,  227,
      223,  222,  221,  220,  219,  216,  215,  209,  207,  201,
      197,  196,  184,  181,  180,   95,   92,   91,   90,   89,
       88,   83,   82,   81,   77,   76,   75,   74,  776,    3,
      776,  776,  776,  776,  776,  776,  776,  776,  776,  776,
      776,  776,  776,  776,  776,  776,  776,  776,  776,  776,
      776,  776,  776,  776,  776,  776,  776,  776,  776,  776,
      776,  776,  776,  776,  776,  776,  776,  776,  776,  776,
      776,  776,  776,  776,  776,  776,  776,  776,  776,  776,

      776,  776,  776
    } ;

static const short int yy_chk[904] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    7,   18,   40,   40,   17,   45,   45,
        7,   49,   49,    7,    7,   13,    7,   17,    7,  774,
       26,   28,   53,   58,   18,   28,   28,    7,    7,    7,
       53,    7,    7,    7,    7,    7,    7,   58,    7,    7,
        7,    7,    7,   30,    7,    7,    7,   62,    7,    7,

       27,   74,   13,   26,   31,   27,   29,   29,   13,   24,
       55,   62,   28,   24,   24,   34,  117,   55,   28,  117,
       30,   33,   33,   31,   27,   59,   30,   31,   27,   32,
       32,   66,   27,   97,   29,   66,   74,   31,   27,   35,
       29,   27,   34,   29,   24,   24,  773,   34,   59,   33,
       24,   24,   24,   25,   25,   33,   68,   97,   35,   39,
       63,   33,   32,   68,   36,   36,   35,   32,   32,   37,
       37,   85,   38,   25,   44,   44,   56,   25,   39,   41,
       41,   25,   39,   85,   36,   48,   48,   25,   36,   37,
       25,   38,   39,   25,  102,   39,  102,   37,   36,   41,

       43,   38,   63,   41,   36,   43,   38,   44,   38,   44,
      132,   56,  132,   41,   42,   46,   57,   56,  104,   48,
       71,  101,  104,   57,   43,   65,   57,   71,  307,   65,
      105,   43,   43,   42,   46,   42,  101,   42,   46,  110,
      105,   46,   46,   70,  771,   42,  307,   42,   46,   65,
       70,   46,   42,   42,   50,   70,   81,  109,  110,   81,
      118,  119,  123,  112,  122,  109,  118,  119,  168,  122,
       81,  122,  112,  147,  168,  123,  147,  133,   50,   50,
       50,  112,   50,  127,   50,   50,  127,  133,  137,  127,
      138,   50,  137,   50,  138,   50,   50,   50,  149,  148,

      138,  148,  149,  148,  155,  163,  149,  159,  159,  155,
      163,  165,  149,  166,  167,  173,  165,  165,  174,  175,
      166,  190,  167,  179,  192,  174,  198,  198,  192,  237,
      190,  255,  202,  175,  242,  179,  202,  208,  208,  271,
      338,  340,  255,  348,  338,  369,  437,  271,  486,  460,
      173,  769,  768,  767,  766,  764,  763,  348,  762,  761,
      760,  759,  758,  756,  754,  753,  751,  749,  237,  747,
      746,  242,  744,  743,  741,  739,  340,  460,  738,  737,
      340,  734,  731,  437,  730,  728,  727,  369,  726,  725,
      486,  724,  723,  721,  720,  718,  716,  715,  712,  710,

      704,  703,  701,  700,  693,  689,  688,  687,  686,  684,
      683,  682,  681,  680,  678,  677,  676,  674,  673,  672,
      670,  666,  665,  664,  663,  662,  660,  658,  657,  656,
      655,  652,  650,  647,  646,  644,  641,  640,  638,  632,
      630,  629,  628,  626,  625,  621,  619,  618,  617,  616,
      612,  608,  606,  604,  603,  602,  600,  599,  598,  597,
      595,  593,  592,  591,  590,  589,  588,  587,  586,  584,
      580,  578,  577,  575,  574,  572,  571,  570,  569,  568,
      567,  566,  565,  564,  562,  559,  558,  557,  556,  555,
      554,  552,  551,  549,  548,  547,  546,  545,  544,  543,

      541,  540,  539,  538,  536,  534,  533,  531,  528,  527,
      523,  522,  521,  517,  516,  514,  513,  512,  511,  510,
      509,  508,  507,  506,  503,  498,  497,  496,  495,  494,
      493,  491,  489,  487,  484,  481,  480,  478,  477,  476,
      475,  473,  472,  471,  470,  469,  468,  466,  465,  464,
      462,  461,  456,  455,  454,  453,  452,  450,  448,  446,
      445,  444,  442,  441,  440,  435,  434,  431,  429,  427,
      425,  424,  422,  420,  418,  417,  416,  415,  414,  413,
      410,  408,  407,  406,  405,  404,  403,  402,  401,  399,
      395,  394,  393,  392,  391,  390,  389,  388,  387,  386,

      384,  383,  381,  380,  379,  378,  377,  375,  374,  373,
      371,  370,  368,  367,  365,  364,  361,  359,  358,  357,
      355,  354,  353,  352,  351,  350,  349,  347,  346,  345,
      344,  343,  342,  341,  339,  337,  336,  335,  334,  333,
      332,  331,  329,  328,  327,  326,  325,  324,  323,  322,
      321,  320,  319,  318,  317,  316,  315,  314,  313,  312,
      311,  310,  309,  308,  306,  305,  304,  303,  301,  300,
      299,  298,  297,  296,  295,  294,  293,  292,  291,  290,
      289,  288,  287,  286,  285,  284,  283,  281,  280,  279,
      278,  277,  276,  275,  274,  273,  272,  270,  269,  265,

      264,  263,  262,  261,  259,  258,  257,  256,  253,  252,
      251,  250,  248,  247,  246,  244,  241,  240,  239,  238,
      236,  234,  233,  232,  231,  230,  229,  228,  227,  226,
      225,  223,  222,  221,  220,  219,  218,  216,  215,  214,
      213,  212,  211,  210,  209,  207,  206,  205,  203,  201,
      200,  199,  197,  196,  195,  194,  193,  191,  189,  188,
      187,  186,  185,  184,  183,  182,  180,  178,  177,  176,
      172,  170,  169,  161,  158,  157,  156,  154,  153,  152,
      151,  146,  144,  143,  142,  141,  140,  139,  136,  134,
      131,  130,  129,  128,  125,  124,  121,  120,  116,  114,

      113,  111,  108,  107,  106,  103,  100,   99,   98,   96,
       93,   92,   91,   90,   89,   87,   86,   84,   83,   82,
       80,   79,   78,   76,   75,   73,   72,   69,   67,   64,
       61,   60,   54,   52,   51,   47,   23,   22,   21,   20,
       19,   16,   15,   14,   12,   11,   10,    9,    3,  776,
      776,  776,  776,  776,  776,  776,  776,  776,  776,  776,
      776,  776,  776,  776,  776,  776,  776,  776,  776,  776,
      776,  776,  776,  776,  776,  776,  776,  776,  776,  776,
      776,  776,  776,  776,  776,  776,  776,  776,  776,  776,
      776,  776,  776,  776,  776,  776,  776,  776,  776,  776,

      776,  776,  776
    } ;

static yy_state_type yy_last_accepting_state;
static YY_CHAR *yy_last_accepting_cpos;

/* the intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0

/* these variables are all declared out here so that section 3 code can
 * manipulate them
 */
/* points to current character in buffer */
static YY_CHAR *yy_c_buf_p = (YY_CHAR *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yyunput YY_PROTO(( YY_CHAR c, YY_CHAR *buf_ptr ));
void yyrestart YY_PROTO(( FILE *input_file ));
void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));

#define yy_new_buffer yy_create_buffer

#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif

YY_DECL
    {
    register yy_state_type yy_current_state;
    register YY_CHAR *yy_cp, *yy_bp;
    register int yy_act;



    if ( yy_init )
	{
	YY_USER_INIT;

	if ( ! yy_start )
	    yy_start = 1;	/* first start state */

	if ( ! yyin )
	    yyin = stdin;

	if ( ! yyout )
	    yyout = stdout;

	if ( yy_current_buffer )
	    yy_init_buffer( yy_current_buffer, yyin );
	else
	    yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_load_buffer_state();

	yy_init = 0;
	}

    while ( 1 )		/* loops until end-of-file is reached */
	{
	yy_cp = yy_c_buf_p;

	/* support of yytext */
	*yy_cp = yy_hold_char;

	/* yy_bp points to the position in yy_ch_buf of the start of the
	 * current run.
	 */
	yy_bp = yy_cp;

	yy_current_state = yy_start;
yy_match:
	do
	    {
	    register YY_CHAR yy_c = yy_ec[*yy_cp];
	    if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	    while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = yy_def[yy_current_state];
		if ( yy_current_state >= 777 )
		    yy_c = yy_meta[yy_c];
		}
	    yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	    ++yy_cp;
	    }
	while ( yy_current_state != 776 );
	yy_cp = yy_last_accepting_cpos;
	yy_current_state = yy_last_accepting_state;

yy_find_action:
	yy_act = yy_accept[yy_current_state];

	YY_DO_BEFORE_ACTION;
	YY_USER_ACTION;

do_action:	/* this label is used only to access EOF actions */


	switch ( yy_act )
	    {
	    case 0: /* must backtrack */
	    /* undo the effects of YY_DO_BEFORE_ACTION */
	    *yy_cp = yy_hold_char;
	    yy_cp = yy_last_accepting_cpos;
	    yy_current_state = yy_last_accepting_state;
	    goto yy_find_action;

case 1:
# line 16 "jive.l"
printf(" stash");
	YY_BREAK
case 2:
# line 17 "jive.l"
printf(" t'row");
	YY_BREAK
case 3:
# line 18 "jive.l"
printf(" honky code");
	YY_BREAK
case 4:
# line 19 "jive.l"
printf(" Isaac");
	YY_BREAK
case 5:
# line 20 "jive.l"
printf(" slow mo-fo");
	YY_BREAK
case 6:
# line 21 "jive.l"
printf(" that slow mo-fo");
	YY_BREAK
case 7:
# line 22 "jive.l"
printf(" snatch'd");
	YY_BREAK
case 8:
# line 23 "jive.l"
printf(" wet-back");
	YY_BREAK
case 9:
# line 24 "jive.l"
printf(" wet-back");
	YY_BREAK
case 10:
# line 25 "jive.l"
printf(" greaser");
	YY_BREAK
case 11:
# line 26 "jive.l"
printf(" greaser");
	YY_BREAK
case 12:
# line 27 "jive.l"
printf(" snatch");
	YY_BREAK
case 13:
# line 28 "jive.l"
printf(" duzn't");
	YY_BREAK
case 14:
# line 29 "jive.l"
printf(" JIBE");
	YY_BREAK
case 15:
# line 30 "jive.l"
printf(" honkyfool");
	YY_BREAK
case 16:
# line 31 "jive.l"
printf(" doodad");
	YY_BREAK
case 17:
# line 32 "jive.l"
printf("e da damn ");
	YY_BREAK
case 18:
# line 33 "jive.l"
printf("a da damn ");
	YY_BREAK
case 19:
# line 34 "jive.l"
printf("t da damn ");
	YY_BREAK
case 20:
# line 35 "jive.l"
printf("d da damn ");
	YY_BREAK
case 21:
# line 36 "jive.l"
printf(" dude ");
	YY_BREAK
case 22:
# line 37 "jive.l"
printf("mama");
	YY_BREAK
case 23:
# line 38 "jive.l"
printf("goat");
	YY_BREAK
case 24:
# line 39 "jive.l"
printf("sump'n");
	YY_BREAK
case 25:
# line 40 "jive.l"
printf(" honky jibe ");
	YY_BREAK
case 26:
# line 41 "jive.l"
printf(" -on rebound- ");
	YY_BREAK
case 27:
# line 42 "jive.l"
printf(" -check y'out latah-");
	YY_BREAK
case 28:
# line 43 "jive.l"
{ sprintf(buf, "%s  Sheeeiit.",yytext); printf(buf); }
	YY_BREAK
case 29:
# line 44 "jive.l"
{ sprintf(buf, "%s  What it is, Mama!",yytext); printf(buf); }
	YY_BREAK
case 30:
# line 45 "jive.l"
{ sprintf(buf, "%s  Ya' know?",yytext); printf(buf); }
	YY_BREAK
case 31:
# line 46 "jive.l"
{ sprintf(buf, "%s  'S coo', bro.",yytext); printf(buf); }
	YY_BREAK
case 32:
# line 47 "jive.l"
{ sprintf(buf, "%s  Ah be baaad...",yytext); printf(buf); }
	YY_BREAK
case 33:
# line 48 "jive.l"
{ sprintf(buf, "%s  Man!",yytext); printf(buf); }
	YY_BREAK
case 34:
# line 49 "jive.l"
{ sprintf(buf, "%s  Slap mah fro!",yytext); printf(buf); }
	YY_BREAK
case 35:
# line 50 "jive.l"
printf("Sho' nuff");
	YY_BREAK
case 36:
# line 51 "jive.l"
printf("sho' nuff");
	YY_BREAK
case 37:
# line 52 "jive.l"
printf(" git");
	YY_BREAK
case 38:
# line 53 "jive.l"
printf("gots'ta");
	YY_BREAK
case 39:
# line 54 "jive.l"
printf("gots'ta ");
	YY_BREAK
case 40:
# line 55 "jive.l"
printf("gots'ta");
	YY_BREAK
case 41:
# line 56 "jive.l"
printf("I's gots'ta be");
	YY_BREAK
case 42:
# line 57 "jive.l"
printf("aint");
	YY_BREAK
case 43:
# line 58 "jive.l"
printf("aint");
	YY_BREAK
case 44:
# line 59 "jive.l"
printf("aint");
	YY_BREAK
case 45:
# line 60 "jive.l"
printf(" is yo'");
	YY_BREAK
case 46:
# line 61 "jive.l"
printf(" you is");
	YY_BREAK
case 47:
# line 62 "jive.l"
printf(" fedora ");
	YY_BREAK
case 48:
# line 63 "jive.l"
printf(" kicker");
	YY_BREAK
case 49:
# line 64 "jive.l"
printf("aint");
	YY_BREAK
case 50:
# line 65 "jive.l"
printf("gots'ta");
	YY_BREAK
case 51:
# line 66 "jive.l"
printf("gots'");
	YY_BREAK
case 52:
# line 67 "jive.l"
printf(" gots'ta");
	YY_BREAK
case 53:
# line 68 "jive.l"
printf("mosey on down");
	YY_BREAK
case 54:
# line 69 "jive.l"
printf(" mosey on down ");
	YY_BREAK
case 55:
# line 70 "jive.l"
printf(".  Right On!  ");
	YY_BREAK
case 56:
# line 71 "jive.l"
printf("steal");
	YY_BREAK
case 57:
# line 72 "jive.l"
printf(" wheels ");
	YY_BREAK
case 58:
# line 73 "jive.l"
printf("roll");
	YY_BREAK
case 59:
# line 74 "jive.l"
printf(" feed da bud ");
	YY_BREAK
case 60:
# line 75 "jive.l"
printf(" brother ");
	YY_BREAK
case 61:
# line 76 "jive.l"
printf(" brother");
	YY_BREAK
case 62:
# line 77 "jive.l"
printf("honky");
	YY_BREAK
case 63:
# line 78 "jive.l"
printf(" gentleman ");
	YY_BREAK
case 64:
# line 79 "jive.l"
printf("supa' fine");
	YY_BREAK
case 65:
# line 80 "jive.l"
printf("sucka'");
	YY_BREAK
case 66:
# line 81 "jive.l"
printf(" wahtahmellun");
	YY_BREAK
case 67:
# line 82 "jive.l"
printf("plantation");
	YY_BREAK
case 68:
# line 83 "jive.l"
printf("dojigger");
	YY_BREAK
case 69:
# line 84 "jive.l"
printf(" alley");
	YY_BREAK
case 70:
# line 85 "jive.l"
printf("clunker");
	YY_BREAK
case 71:
# line 86 "jive.l"
printf("o'");
	YY_BREAK
case 72:
# line 87 "jive.l"
printf("wasted");
	YY_BREAK
case 73:
# line 88 "jive.l"
printf("super-dude");
	YY_BREAK
case 74:
# line 89 "jive.l"
printf("super honcho");
	YY_BREAK
case 75:
# line 90 "jive.l"
printf("hosed");
	YY_BREAK
case 76:
# line 91 "jive.l"
printf("guv'ment");
	YY_BREAK
case 77:
# line 92 "jive.l"
printf("knowed");
	YY_BREAK
case 78:
# line 93 "jive.l"
printf("a'cuz");
	YY_BREAK
case 79:
# line 94 "jive.l"
printf("A'cuz");
	YY_BREAK
case 80:
# line 95 "jive.l"
printf("yo'");
	YY_BREAK
case 81:
# line 96 "jive.l"
printf("Yo'");
	YY_BREAK
case 82:
# line 97 "jive.l"
printf("foe");
	YY_BREAK
case 83:
# line 98 "jive.l"
printf("gots");
	YY_BREAK
case 84:
# line 99 "jive.l"
printf("ain't");
	YY_BREAK
case 85:
# line 100 "jive.l"
printf("yung");
	YY_BREAK
case 86:
# line 101 "jive.l"
printf("ya'");
	YY_BREAK
case 87:
# line 102 "jive.l"
printf("You's");
	YY_BREAK
case 88:
# line 103 "jive.l"
printf("fust");
	YY_BREAK
case 89:
# line 104 "jive.l"
printf("honky pigs");
	YY_BREAK
case 90:
# line 105 "jive.l"
printf(" chittlin'");
	YY_BREAK
case 91:
# line 106 "jive.l"
printf(" eyeball");
	YY_BREAK
case 92:
# line 107 "jive.l"
printf("scribble");
	YY_BREAK
case 93:
# line 108 "jive.l"
printf("d");
	YY_BREAK
case 94:
# line 109 "jive.l"
printf("D");
	YY_BREAK
case 95:
# line 110 "jive.l"
printf("in'");
	YY_BREAK
case 96:
# line 111 "jive.l"
printf(" some ");
	YY_BREAK
case 97:
# line 112 "jive.l"
printf(" t'");
	YY_BREAK
case 98:
# line 113 "jive.l"
printf("shun");
	YY_BREAK
case 99:
# line 114 "jive.l"
printf(" mos' ");
	YY_BREAK
case 100:
# line 115 "jive.l"
printf(" fum");
	YY_BREAK
case 101:
# line 116 "jive.l"
printf(" cuz' ");
	YY_BREAK
case 102:
# line 117 "jive.l"
printf("youse");
	YY_BREAK
case 103:
# line 118 "jive.l"
printf("Youse");
	YY_BREAK
case 104:
# line 119 "jive.l"
printf("coo'");
	YY_BREAK
case 105:
# line 120 "jive.l"
printf("coo'");
	YY_BREAK
case 106:
# line 121 "jive.l"
printf("a' ");
	YY_BREAK
case 107:
# line 122 "jive.l"
printf("knode");
	YY_BREAK
case 108:
# line 123 "jive.l"
printf("wants'");
	YY_BREAK
case 109:
# line 124 "jive.l"
printf("whup'");
	YY_BREAK
case 110:
# line 125 "jive.l"
printf("'sp");
	YY_BREAK
case 111:
# line 126 "jive.l"
printf("'s");
	YY_BREAK
case 112:
# line 127 "jive.l"
printf(" 's");
	YY_BREAK
case 113:
# line 128 "jive.l"
printf(" 'es");
	YY_BREAK
case 114:
# line 129 "jive.l"
printf("likes");
	YY_BREAK
case 115:
# line 130 "jive.l"
printf("dun did");
	YY_BREAK
case 116:
# line 131 "jive.l"
printf("kind'a");
	YY_BREAK
case 117:
# line 132 "jive.l"
printf("honky chicks");
	YY_BREAK
case 118:
# line 133 "jive.l"
printf(" dudes ");
	YY_BREAK
case 119:
# line 134 "jive.l"
printf(" dudes ");
	YY_BREAK
case 120:
# line 135 "jive.l"
printf(" dude ");
	YY_BREAK
case 121:
# line 136 "jive.l"
printf("honky chick");
	YY_BREAK
case 122:
# line 137 "jive.l"
printf("wasted");
	YY_BREAK
case 123:
# line 138 "jive.l"
printf("baaaad");
	YY_BREAK
case 124:
# line 139 "jive.l"
printf("jimmey ");
	YY_BREAK
case 125:
# line 140 "jive.l"
printf("jimmey'd ");
	YY_BREAK
case 126:
# line 141 "jive.l"
printf(" real");
	YY_BREAK
case 127:
# line 142 "jive.l"
printf("puh'");
	YY_BREAK
case 128:
# line 143 "jive.l"
printf("puh'");
	YY_BREAK
case 129:
# line 144 "jive.l"
printf("o'");
	YY_BREAK
case 130:
# line 145 "jive.l"
printf(" kin");
	YY_BREAK
case 131:
# line 146 "jive.l"
printf("plum ");
	YY_BREAK
case 132:
# line 147 "jive.l"
printf("Mo-town");
	YY_BREAK
case 133:
# line 148 "jive.l"
printf("da' cave");
	YY_BREAK
case 134:
# line 149 "jive.l"
printf(" recon'");
	YY_BREAK
case 135:
# line 150 "jive.l"
printf("Nap-town");
	YY_BREAK
case 136:
# line 151 "jive.l"
printf(" Buckwheat");
	YY_BREAK
case 137:
# line 152 "jive.l"
printf(" Liva' Lips ");
	YY_BREAK
case 138:
# line 153 "jive.l"
printf(" dat fine soul ");
	YY_BREAK
case 139:
# line 154 "jive.l"
printf(" Amos ");
	YY_BREAK
case 140:
# line 155 "jive.l"
printf("Leroy");
	YY_BREAK
case 141:
# line 156 "jive.l"
printf("dat fine femahnaine ladee");
	YY_BREAK
case 142:
# line 157 "jive.l"
printf("Raz'tus ");
	YY_BREAK
case 143:
# line 158 "jive.l"
printf(" Fuh'rina");
	YY_BREAK
case 144:
# line 159 "jive.l"
printf("Kingfish");
	YY_BREAK
case 145:
# line 160 "jive.l"
printf("Issac");
	YY_BREAK
case 146:
# line 161 "jive.l"
printf("Rolo");
	YY_BREAK
case 147:
# line 162 "jive.l"
printf(" Bo-Jangles ");
	YY_BREAK
case 148:
# line 163 "jive.l"
printf(" Snow Flake");
	YY_BREAK
case 149:
# line 164 "jive.l"
printf("Remus");
	YY_BREAK
case 150:
# line 165 "jive.l"
printf("Massa' ");
	YY_BREAK
case 151:
# line 166 "jive.l"
printf("Massa' ");
	YY_BREAK
case 152:
# line 167 "jive.l"
printf("liva' lips");
	YY_BREAK
case 153:
# line 168 "jive.l"
printf("wiz'");
	YY_BREAK
case 154:
# line 169 "jive.l"
printf("wiz'");
	YY_BREAK
case 155:
# line 170 "jive.l"
printf("dat commie rag");
	YY_BREAK
case 156:
# line 171 "jive.l"
printf("bugger'd");
	YY_BREAK
case 157:
# line 172 "jive.l"
printf("funky ");
	YY_BREAK
case 158:
# line 173 "jive.l"
printf("boogy ");
	YY_BREAK
case 159:
# line 174 "jive.l"
printf(" crib");
	YY_BREAK
case 160:
# line 175 "jive.l"
printf("ax'");
	YY_BREAK
case 161:
# line 176 "jive.l"
printf(" so's ");
	YY_BREAK
case 162:
# line 177 "jive.l"
printf("'haid");
	YY_BREAK
case 163:
# line 178 "jive.l"
printf("main man");
	YY_BREAK
case 164:
# line 179 "jive.l"
printf("mama");
	YY_BREAK
case 165:
# line 180 "jive.l"
printf("sucka's");
	YY_BREAK
case 166:
# line 181 "jive.l"
printf("bre'd");
	YY_BREAK
case 167:
# line 182 "jive.l"
{	*(yytext+1) = ',';
				sprintf(buf, "%s dig dis:",yytext);
				printf(buf);
			}
	YY_BREAK
case 168:
# line 186 "jive.l"
printf("begina'");
	YY_BREAK
case 169:
# line 187 "jive.l"
printf("transista'");
	YY_BREAK
case 170:
# line 188 "jive.l"
printf(" uh ");
	YY_BREAK
case 171:
# line 189 "jive.l"
printf("whut");
	YY_BREAK
case 172:
# line 190 "jive.l"
printf("duz");
	YY_BREAK
case 173:
# line 191 "jive.l"
printf("wuz");
	YY_BREAK
case 174:
# line 192 "jive.l"
printf(" wuz");
	YY_BREAK
case 175:
# line 193 "jive.l"
printf("dig it");
	YY_BREAK
case 176:
# line 194 "jive.l"
printf("dig it");
	YY_BREAK
case 177:
# line 195 "jive.l"
printf(" mah'");
	YY_BREAK
case 178:
# line 196 "jive.l"
printf(" ah' ");
	YY_BREAK
case 179:
# line 197 "jive.l"
printf("meta-fuckin'");
	YY_BREAK
case 180:
# line 198 "jive.l"
printf("fro");
	YY_BREAK
case 181:
# line 199 "jive.l"
printf("rap");
	YY_BREAK
case 182:
# line 200 "jive.l"
printf("beat");
	YY_BREAK
case 183:
# line 201 "jive.l"
printf("hoop");
	YY_BREAK
case 184:
# line 202 "jive.l"
printf("ball");
	YY_BREAK
case 185:
# line 203 "jive.l"
printf("homey");
	YY_BREAK
case 186:
# line 204 "jive.l"
printf("farm");
	YY_BREAK
case 187:
# line 205 "jive.l"
printf("Man");
	YY_BREAK
case 188:
# line 206 "jive.l"
printf("wanna");
	YY_BREAK
case 189:
# line 207 "jive.l"
printf("be hankerin' aftah");
	YY_BREAK
case 190:
# line 208 "jive.l"
printf("sheeit");
	YY_BREAK
case 191:
# line 209 "jive.l"
printf("Sheeit");
	YY_BREAK
case 192:
# line 210 "jive.l"
printf("big-ass");
	YY_BREAK
case 193:
# line 211 "jive.l"
printf("bad-ass");
	YY_BREAK
case 194:
# line 212 "jive.l"
printf("little-ass");
	YY_BREAK
case 195:
# line 213 "jive.l"
printf("radical");
	YY_BREAK
case 196:
# line 214 "jive.l"
printf(" be ");
	YY_BREAK
case 197:
# line 215 "jive.l"
printf("booze");
	YY_BREAK
case 198:
# line 216 "jive.l"
printf("scribblin'");
	YY_BREAK
case 199:
# line 217 "jive.l"
printf("issue of GQ");
	YY_BREAK
case 200:
# line 218 "jive.l"
printf("sheet");
	YY_BREAK
case 201:
# line 219 "jive.l"
printf("down");
	YY_BREAK
case 202:
# line 220 "jive.l"
printf("waaay down");
	YY_BREAK
case 203:
# line 221 "jive.l"
printf("boogie");
	YY_BREAK
case 204:
# line 222 "jive.l"
printf("'Sup, dude");
	YY_BREAK
case 205:
# line 223 "jive.l"
printf("pink Cadillac");
	YY_BREAK
case 206:
# line 224 "jive.l"
printf(yytext);
	YY_BREAK
case 207:
# line 225 "jive.l"
printf("\n");
	YY_BREAK
case 208:
# line 226 "jive.l"
printf("\n");
	YY_BREAK
case 209:
# line 228 "jive.l"
ECHO;
	YY_BREAK
case YY_STATE_EOF(INITIAL):
    yyterminate();

	    case YY_END_OF_BUFFER:
		{
		/* amount of text matched not including the EOB char */
		int yy_amount_of_matched_text = yy_cp - yytext - 1;

		/* undo the effects of YY_DO_BEFORE_ACTION */
		*yy_cp = yy_hold_char;

		/* note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the end-
		 * of-buffer state).  Contrast this with the test in yyinput().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
		    /* this was really a NUL */
		    {
		    yy_state_type yy_next_state;

		    yy_c_buf_p = yytext + yy_amount_of_matched_text;

		    yy_current_state = yy_get_previous_state();

		    /* okay, we're now positioned to make the
		     * NUL transition.  We couldn't have
		     * yy_get_previous_state() go ahead and do it
		     * for us because it doesn't know how to deal
		     * with the possibility of jamming (and we
		     * don't want to build jamming into it because
		     * then it will run more slowly)
		     */

		    yy_next_state = yy_try_NUL_trans( yy_current_state );

		    yy_bp = yytext + YY_MORE_ADJ;

		    if ( yy_next_state )
			{
			/* consume the NUL */
			yy_cp = ++yy_c_buf_p;
			yy_current_state = yy_next_state;
			goto yy_match;
			}

		    else
			{
			    yy_cp = yy_last_accepting_cpos;
			    yy_current_state = yy_last_accepting_state;
			goto yy_find_action;
			}
		    }

		else switch ( yy_get_next_buffer() )
		    {
		    case EOB_ACT_END_OF_FILE:
			{
			yy_did_buffer_switch_on_eof = 0;

			if ( yywrap() )
			    {
			    /* note: because we've taken care in
			     * yy_get_next_buffer() to have set up yytext,
			     * we can now set up yy_c_buf_p so that if some
			     * total hoser (like flex itself) wants
			     * to call the scanner after we return the
			     * YY_NULL, it'll still work - another YY_NULL
			     * will get returned.
			     */
			    yy_c_buf_p = yytext + YY_MORE_ADJ;

			    yy_act = YY_STATE_EOF((yy_start - 1) / 2);
			    goto do_action;
			    }

			else
			    {
			    if ( ! yy_did_buffer_switch_on_eof )
				YY_NEW_FILE;
			    }
			}
			break;

		    case EOB_ACT_CONTINUE_SCAN:
			yy_c_buf_p = yytext + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			yy_cp = yy_c_buf_p;
			yy_bp = yytext + YY_MORE_ADJ;
			goto yy_match;

		    case EOB_ACT_LAST_MATCH:
			yy_c_buf_p =
			    &yy_current_buffer->yy_ch_buf[yy_n_chars];

			yy_current_state = yy_get_previous_state();

			yy_cp = yy_c_buf_p;
			yy_bp = yytext + YY_MORE_ADJ;
			goto yy_find_action;
		    }
		break;
		}

	    default:
#ifdef FLEX_DEBUG
		printf( "action # %d\n", yy_act );
#endif
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	    }
	}
    }


/* yy_get_next_buffer - try to read in a new buffer
 *
 * synopsis
 *     int yy_get_next_buffer();
 *     
 * returns a code representing an action
 *     EOB_ACT_LAST_MATCH - 
 *     EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *     EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()

    {
    register YY_CHAR *dest = yy_current_buffer->yy_ch_buf;
    register YY_CHAR *source = yytext - 1; /* copy prev. char, too */
    register int number_to_move, i;
    int ret_val;

    if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
	YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

    /* try to read more data */

    /* first move last chars to start of buffer */
    number_to_move = yy_c_buf_p - yytext;

    for ( i = 0; i < number_to_move; ++i )
	*(dest++) = *(source++);

    if ( yy_current_buffer->yy_eof_status != EOF_NOT_SEEN )
	/* don't do the read, it's not guaranteed to return an EOF,
	 * just force an EOF
	 */
	yy_n_chars = 0;

    else
	{
	int num_to_read = yy_current_buffer->yy_buf_size - number_to_move - 1;

	if ( num_to_read > YY_READ_BUF_SIZE )
	    num_to_read = YY_READ_BUF_SIZE;

	else if ( num_to_read <= 0 )
	    YY_FATAL_ERROR( "fatal error - scanner input buffer overflow" );

	/* read in more data */
	YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
		  yy_n_chars, num_to_read );
	}

    if ( yy_n_chars == 0 )
	{
	if ( number_to_move == 1 )
	    {
	    ret_val = EOB_ACT_END_OF_FILE;
	    yy_current_buffer->yy_eof_status = EOF_DONE;
	    }

	else
	    {
	    ret_val = EOB_ACT_LAST_MATCH;
	    yy_current_buffer->yy_eof_status = EOF_PENDING;
	    }
	}

    else
	ret_val = EOB_ACT_CONTINUE_SCAN;

    yy_n_chars += number_to_move;
    yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
    yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

    /* yytext begins at the second character in yy_ch_buf; the first
     * character is the one which preceded it before reading in the latest
     * buffer; it needs to be kept around in case it's a newline, so
     * yy_get_previous_state() will have with '^' rules active
     */

    yytext = &yy_current_buffer->yy_ch_buf[1];

    return ( ret_val );
    }


/* yy_get_previous_state - get the state just before the EOB char was reached
 *
 * synopsis
 *     yy_state_type yy_get_previous_state();
 */

static yy_state_type yy_get_previous_state()

    {
    register yy_state_type yy_current_state;
    register YY_CHAR *yy_cp;

    yy_current_state = yy_start;

    for ( yy_cp = yytext + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
	{
	register YY_CHAR yy_c = (*yy_cp ? yy_ec[*yy_cp] : 1);
	if ( yy_accept[yy_current_state] )
	    {
	    yy_last_accepting_state = yy_current_state;
	    yy_last_accepting_cpos = yy_cp;
	    }
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
	    {
	    yy_current_state = yy_def[yy_current_state];
	    if ( yy_current_state >= 777 )
		yy_c = yy_meta[yy_c];
	    }
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	}

    return ( yy_current_state );
    }


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *     next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( register yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
register yy_state_type yy_current_state;
#endif

    {
    register int yy_is_jam;
    register YY_CHAR *yy_cp = yy_c_buf_p;

    register YY_CHAR yy_c = 1;
    if ( yy_accept[yy_current_state] )
	{
	yy_last_accepting_state = yy_current_state;
	yy_last_accepting_cpos = yy_cp;
	}
    while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
	{
	yy_current_state = yy_def[yy_current_state];
	if ( yy_current_state >= 777 )
	    yy_c = yy_meta[yy_c];
	}
    yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
    yy_is_jam = (yy_current_state == 776);

    return ( yy_is_jam ? 0 : yy_current_state );
    }


#ifdef YY_USE_PROTOS
static void yyunput( YY_CHAR c, register YY_CHAR *yy_bp )
#else
static void yyunput( c, yy_bp )
YY_CHAR c;
register YY_CHAR *yy_bp;
#endif

    {
    register YY_CHAR *yy_cp = yy_c_buf_p;

    /* undo effects of setting up yytext */
    *yy_cp = yy_hold_char;

    if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
	{ /* need to shift things up to make room */
	register int number_to_move = yy_n_chars + 2; /* +2 for EOB chars */
	register YY_CHAR *dest =
	    &yy_current_buffer->yy_ch_buf[yy_current_buffer->yy_buf_size + 2];
	register YY_CHAR *source =
	    &yy_current_buffer->yy_ch_buf[number_to_move];

	while ( source > yy_current_buffer->yy_ch_buf )
	    *--dest = *--source;

	yy_cp += dest - source;
	yy_bp += dest - source;
	yy_n_chars = yy_current_buffer->yy_buf_size;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
	    YY_FATAL_ERROR( "flex scanner push-back overflow" );
	}

    if ( yy_cp > yy_bp && yy_cp[-1] == '\n' )
	yy_cp[-2] = '\n';

    *--yy_cp = c;

    /* note: the formal parameter *must* be called "yy_bp" for this
     *       macro to now work correctly
     */
    YY_DO_BEFORE_ACTION; /* set up yytext again */
    }


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif

    {
    int c;
    YY_CHAR *yy_cp = yy_c_buf_p;

    *yy_cp = yy_hold_char;

    if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
	{
	/* yy_c_buf_p now points to the character we want to return.
	 * If this occurs *before* the EOB characters, then it's a
	 * valid NUL; if not, then we've hit the end of the buffer.
	 */
	if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
	    /* this was really a NUL */
	    *yy_c_buf_p = '\0';

	else
	    { /* need more input */
	    yytext = yy_c_buf_p;
	    ++yy_c_buf_p;

	    switch ( yy_get_next_buffer() )
		{
		case EOB_ACT_END_OF_FILE:
		    {
		    if ( yywrap() )
			{
			yy_c_buf_p = yytext + YY_MORE_ADJ;
			return ( EOF );
			}

		    YY_NEW_FILE;

#ifdef __cplusplus
		    return ( yyinput() );
#else
		    return ( input() );
#endif
		    }
		    break;

		case EOB_ACT_CONTINUE_SCAN:
		    yy_c_buf_p = yytext + YY_MORE_ADJ;
		    break;

		case EOB_ACT_LAST_MATCH:
#ifdef __cplusplus
		    YY_FATAL_ERROR( "unexpected last match in yyinput()" );
#else
		    YY_FATAL_ERROR( "unexpected last match in input()" );
#endif
		}
	    }
	}

    c = *yy_c_buf_p;
    yy_hold_char = *++yy_c_buf_p;

    return ( c );
    }


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif

    {
    yy_init_buffer( yy_current_buffer, input_file );
    yy_load_buffer_state();
    }


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif

    {
    if ( yy_current_buffer == new_buffer )
	return;

    if ( yy_current_buffer )
	{
	/* flush out information for old buffer */
	*yy_c_buf_p = yy_hold_char;
	yy_current_buffer->yy_buf_pos = yy_c_buf_p;
	yy_current_buffer->yy_n_chars = yy_n_chars;
	}

    yy_current_buffer = new_buffer;
    yy_load_buffer_state();

    /* we don't actually know whether we did this switch during
     * EOF (yywrap()) processing, but the only time this flag
     * is looked at is after yywrap() is called, so it's safe
     * to go ahead and always set it.
     */
    yy_did_buffer_switch_on_eof = 1;
    }


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif

    {
    yy_n_chars = yy_current_buffer->yy_n_chars;
    yytext = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
    yyin = yy_current_buffer->yy_input_file;
    yy_hold_char = *yy_c_buf_p;
    }


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif

    {
    YY_BUFFER_STATE b;

    b = (YY_BUFFER_STATE) malloc( sizeof( struct yy_buffer_state ) );

    if ( ! b )
	YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

    b->yy_buf_size = size;

    /* yy_ch_buf has to be 2 characters longer than the size given because
     * we need to put in 2 end-of-buffer characters.
     */
    b->yy_ch_buf = (YY_CHAR *) malloc( (unsigned) (b->yy_buf_size + 2) );

    if ( ! b->yy_ch_buf )
	YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

    yy_init_buffer( b, file );

    return ( b );
    }


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif

    {
    if ( b == yy_current_buffer )
	yy_current_buffer = (YY_BUFFER_STATE) 0;

    free( (char *) b->yy_ch_buf );
    free( (char *) b );
    }


#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif

    {
    b->yy_input_file = file;

    /* we put in the '\n' and start reading from [1] so that an
     * initial match-at-newline will be true.
     */

    b->yy_ch_buf[0] = '\n';
    b->yy_n_chars = 1;

    /* we always need two end-of-buffer characters.  The first causes
     * a transition to the end-of-buffer state.  The second causes
     * a jam in that state.
     */
    b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;
    b->yy_ch_buf[2] = YY_END_OF_BUFFER_CHAR;

    b->yy_buf_pos = &b->yy_ch_buf[1];

    b->yy_eof_status = EOF_NOT_SEEN;
    }
# line 228 "jive.l"


main()
{
	yylex();
}
