/* A lexical scanner generated by flex */

/* scanner skeleton version:
 * $Header: /usr/fsys/odin/a/vern/flex/RCS/flex.skel,v 2.16 90/08/03 14:09:36 vern Exp $
 */

#define FLEX_SCANNER

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <osfcn.h>

/* use prototypes in function declarations */
#define YY_USE_PROTOS

/* the "const" storage-class-modifier is valid */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#ifdef __STDC__

#ifdef __GNUC__
#include <stddef.h>
void *malloc( size_t );
void free( void* );
#else
#include <stdlib.h>
#endif	/* __GNUC__ */

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */


#ifdef __TURBOC__
#define YY_USE_CONST
#endif


#ifndef YY_USE_CONST
#define const
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
/* we can't get here if it's an ANSI C compiler, or a C++ compiler,
 * so it's got to be a K&R compiler, and therefore there's no standard
 * place from which to include these definitions
 */
char *malloc();
int free();
int read();
#endif


/* amount of stuff to slurp up with each read */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* returned upon end-of-file */
#define YY_END_TOK 0

/* copy whatever the last rule matched to the standard output */

/* cast to (char *) is because for 8-bit chars, yytext is (unsigned char *) */
/* this used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite()
 */
#define ECHO (void) fwrite( (char *) yytext, yyleng, 1, yyout )

/* gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#define YY_INPUT(buf,result,max_size) \
	if ( (result = read( fileno(yyin), (char *) buf, max_size )) < 0 ) \
	    YY_FATAL_ERROR( "read() in flex scanner failed" );
#define YY_NULL 0

/* no semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#define yyterminate() return ( YY_NULL )

/* report a fatal error */

/* The funky do-while is used to turn this macro definition into
 * a single C statement (which needs a semi-colon terminator).
 * This avoids problems with code like:
 *
 * 	if ( something_happens )
 *		YY_FATAL_ERROR( "oops, the something happened" );
 *	else
 *		everything_okay();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the YY_FATAL_ERROR() call.
 */

#define YY_FATAL_ERROR(msg) \
	do \
		{ \
		(void) fputs( msg, stderr ); \
		(void) putc( '\n', stderr ); \
		exit( 1 ); \
		} \
	while ( 0 )

/* default yywrap function - always treat EOF as an EOF */
#define yywrap() 1

/* enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN
 */
#define BEGIN yy_start = 1 + 2 *

/* action number for EOF rule of a given start state */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* special action meaning "start processing a new file" */
#define YY_NEW_FILE \
	do \
		{ \
		yy_init_buffer( yy_current_buffer, yyin ); \
		yy_load_buffer_state(); \
		} \
	while ( 0 )

/* default declaration of generated scanner - a define so the user can
 * easily add parameters
 */
#define YY_DECL int yylex YY_PROTO(( void )) 

/* code executed at the end of each rule */
#define YY_BREAK break;

#define YY_END_OF_BUFFER_CHAR 0

#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE (YY_READ_BUF_SIZE * 2) /* size of default input buffer */
#endif

typedef struct yy_buffer_state *YY_BUFFER_STATE;

#define YY_CHAR char
# line 1 "valspeak.l"
#define INITIAL 0
# line 4 "valspeak.l"

/* done after the current pattern has been matched and before the
 * corresponding action - sets up yytext
 */
#define YY_DO_BEFORE_ACTION \
	yytext = yy_bp; \
	yyleng = yy_cp - yy_bp; \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* return all but the first 'n' matched characters back to the input stream */
#define yyless(n) \
	do \
		{ \
		/* undo effects of setting up yytext */ \
		*yy_cp = yy_hold_char; \
		yy_c_buf_p = yy_cp = yy_bp + n; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext )


struct yy_buffer_state
    {
    FILE *yy_input_file;

    YY_CHAR *yy_ch_buf;		/* input buffer */
    YY_CHAR *yy_buf_pos;	/* current position in input buffer */

    /* size of input buffer in bytes, not including room for EOB characters*/
    int yy_buf_size;	

    /* number of characters read into yy_ch_buf, not including EOB characters */
    int yy_n_chars;

    int yy_eof_status;		/* whether we've seen an EOF on this buffer */
#define EOF_NOT_SEEN 0
    /* "pending" happens when the EOF has been seen but there's still
     * some text process
     */
#define EOF_PENDING 1
#define EOF_DONE 2
    };

static YY_BUFFER_STATE yy_current_buffer;

/* we provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state"
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed */
static YY_CHAR yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */



#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

#ifndef YY_USER_INIT
#define YY_USER_INIT
#endif

extern YY_CHAR *yytext;
extern int yyleng;
extern FILE *yyin, *yyout;

YY_CHAR *yytext;
int yyleng;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

#define YY_END_OF_BUFFER 64
typedef int yy_state_type;
static const short int yy_accept[270] =
    {   0,
        0,    0,   64,   62,   63,   62,   60,   62,   62,   62,
       62,   62,   62,   62,   62,   62,   62,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   59,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   50,    0,   52,    0,   53,    0,    0,   57,
        0,   61,    1,    2,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,   13,    0,    0,    0,    0,
       28,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   48,   49,    0,   54,    0,   55,   58,    3,
        4,    0,    0,    5,    0,    0,    8,    9,   10,    0,
        0,   14,   15,   16,   17,    0,    0,    0,    0,   33,
        0,    0,    0,    0,   38,   39,    0,    0,    0,    0,
        0,   44,   45,   46,   24,    0,    0,    0,    0,    0,
       56,    0,    0,    6,    0,   11,   12,   29,    0,   31,
       32,    0,    0,   36,    0,    0,    0,    0,    0,    0,

        0,   47,    0,    0,   51,    0,    0,    7,    0,   34,
        0,   37,   40,   41,   42,    0,    0,    0,    0,    0,
       18,    0,    0,   35,    0,    0,   43,   25,    0,    0,
        0,    0,    0,    0,    0,   26,    0,   19,    0,    0,
        0,    0,   27,    0,   22,    0,    0,   30,    0,    0,
        0,    0,    0,    0,    0,   23,    0,    0,    0,    0,
        0,    0,    0,   20,    0,    0,    0,   21,    0
    } ;

static const YY_CHAR yy_ec[128] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    4,    1,    1,    1,    1,    1,    5,    1,
        1,    1,    1,    6,    1,    7,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    8,    1,    1,    1,    1,
        1,    9,   10,    1,    1,    1,    1,   11,    1,    1,
        1,    1,   12,   13,    1,    1,   14,    1,   15,    1,
        1,    1,    1,    1,    1,    1,   16,   17,   18,   19,

       20,   21,   22,   23,   24,    1,   25,   26,   27,   28,
       29,   30,    1,   31,   32,   33,   34,   35,   36,    1,
       37,    1,    1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[38] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1
    } ;

static const short int yy_base[271] =
    {   0,
        0,   23,  279,  280,  280,   31,  280,  275,  243,  256,
      272,  245,   16,  250,  252,  251,  242,   27,  253,  244,
       17,   41,   49,   48,    0,   61,   59,  247,  246,   51,
      242,  244,   69,  243,  280,  229,  258,  234,  253,  238,
      226,   62,  253,  223,  232,  234,  230,   11,   63,  220,
      224,  220,  217,  218,   67,  209,  214,  217,  209,  209,
      238,  209,  223,   64,  218,  202,  204,  219,  216,  230,
      203,  215,  201,  198,  208,  196,   71,  202,  199,  196,
      191,  219,  280,  197,  280,  217,  280,  188,  186,  280,
      211,  280,  280,  280,  179,  195,    2,  211,  180,  179,

      192,  184,  190,  192,  175,  280,   14,   15,  174,  185,
      280,  182,  168,  199,  184,  167,  175,  174,  164,  176,
      159,  164,  167,  158,  175,  187,  152,  155,   16,  156,
      160,  180,  280,  280,  159,  280,  163,  280,  280,  280,
      280,  165,  148,  280,  143,  156,  280,  280,  280,  145,
      145,  280,  280,  280,  280,  156,  144,  154,  153,  280,
      152,  147,  150,  151,  280,  280,  152,  141,  140,  139,
      136,  280,  280,  280,  280,  158,  143,  158,  127,  139,
      280,  138,  154,  280,  119,  280,  280,  280,  135,  280,
      280,  151,  125,  280,  149,  114,  130,  112,  129,  125,

      113,  280,  128,  141,  280,  140,  125,  280,  109,  280,
      118,  280,  280,  280,  280,   94,  119,  135,  117,  119,
      280,  115,  101,  280,   83,  128,  280,  280,  129,  111,
      127,  105,  108,  111,   93,  280,  122,  280,   96,  120,
       86,  117,  280,   97,  280,   98,   85,  280,  114,   96,
       99,   97,  110,   77,   91,  280,   90,   89,  104,   77,
       87,   68,   40,  280,   25,    0,   20,  280,  280,    0
    } ;

static const short int yy_def[271] =
    {   0,
      270,  270,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,

      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,

      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  269,    0,  269
    } ;

static const short int yy_nxt[318] =
    {   0,
        4,    5,    6,    7,  142,    8,  143,    9,   10,   11,
       12,   13,   14,   15,   16,   62,  152,  154,  175,   63,
      153,  155,  268,   17,    5,    6,    7,  267,    8,   95,
        9,   10,   11,   12,   13,   14,   15,   16,   40,   41,
       51,   96,   46,  176,  266,   52,   17,   18,   19,   20,
       47,   21,   22,   23,   24,   48,   25,   26,   27,  265,
       28,   29,   30,   31,   53,   32,   33,   34,   57,   54,
      264,   55,   58,   73,   56,   60,   64,   59,   68,   61,
       65,   88,   69,   74,   77,   89,  104,   70,   78,   66,
       97,  114,   79,   98,   67,  105,  225,   80,  128,  233,

      115,  250,  129,  263,  262,  234,  261,  251,  260,  259,
      258,  257,  256,  255,  254,  253,  252,  249,  248,  247,
      246,  226,  245,  244,  243,  242,  241,  240,  239,  238,
      237,  236,  235,  232,  231,  230,  229,  228,  227,  224,
      223,  222,  221,  220,  219,  218,  217,  216,  215,  214,
      213,  212,  211,  210,  209,  208,  207,  206,  205,  204,
      203,  202,  201,  200,  199,  198,  197,  196,  195,  194,
      193,  192,  191,  190,  189,  188,  187,  186,  185,  184,
      183,  182,  181,  180,  179,  178,  177,  174,  173,  172,
      171,  170,  169,  168,  167,  166,  165,  164,  163,  162,

      161,  160,  159,  158,  157,  156,  151,  150,  149,  148,
      147,  146,  145,  144,  141,  140,  139,  138,  137,  136,
      135,  134,  133,  132,  131,  130,  127,  126,  125,  124,
      123,  122,  121,  120,  119,  118,  117,  116,  113,  112,
      111,  110,  109,  108,  107,  106,  103,  102,  101,  100,
       99,   94,   93,   92,   91,   90,   87,   86,   85,   84,
       83,   82,   81,   76,   75,   72,   71,   50,   49,   45,
       44,   43,   42,   39,   38,   37,   36,   35,  269,    3,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,

      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  269
    } ;

static const short int yy_chk[318] =
    {   0,
      270,    1,    1,    1,   97,    1,   97,    1,    1,    1,
        1,    1,    1,    1,    1,   25,  107,  108,  129,   25,
      107,  108,  267,    1,    2,    2,    2,  266,    2,   48,
        2,    2,    2,    2,    2,    2,    2,    2,   13,   13,
       21,   48,   18,  129,  265,   21,    2,    6,    6,    6,
       18,    6,    6,    6,    6,   18,    6,    6,    6,  263,
        6,    6,    6,    6,   22,    6,    6,    6,   23,   22,
      262,   22,   23,   30,   22,   24,   26,   23,   27,   24,
       26,   42,   27,   30,   33,   42,   55,   27,   33,   26,
       49,   64,   33,   49,   26,   55,  216,   33,   77,  225,

       64,  247,   77,  261,  260,  225,  259,  247,  258,  257,
      255,  254,  253,  252,  251,  250,  249,  246,  244,  242,
      241,  216,  240,  239,  237,  235,  234,  233,  232,  231,
      230,  229,  226,  223,  222,  220,  219,  218,  217,  211,
      209,  207,  206,  204,  203,  201,  200,  199,  198,  197,
      196,  195,  193,  192,  189,  185,  183,  182,  180,  179,
      178,  177,  176,  171,  170,  169,  168,  167,  164,  163,
      162,  161,  159,  158,  157,  156,  151,  150,  146,  145,
      143,  142,  137,  135,  132,  131,  130,  128,  127,  126,
      125,  124,  123,  122,  121,  120,  119,  118,  117,  116,

      115,  114,  113,  112,  110,  109,  105,  104,  103,  102,
      101,  100,   99,   98,   96,   95,   91,   89,   88,   86,
       84,   82,   81,   80,   79,   78,   76,   75,   74,   73,
       72,   71,   70,   69,   68,   67,   66,   65,   63,   62,
       61,   60,   59,   58,   57,   56,   54,   53,   52,   51,
       50,   47,   46,   45,   44,   43,   41,   40,   39,   38,
       37,   36,   34,   32,   31,   29,   28,   20,   19,   17,
       16,   15,   14,   12,   11,   10,    9,    8,    3,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,

      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  269
    } ;

static yy_state_type yy_last_accepting_state;
static YY_CHAR *yy_last_accepting_cpos;

/* the intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0

/* these variables are all declared out here so that section 3 code can
 * manipulate them
 */
/* points to current character in buffer */
static YY_CHAR *yy_c_buf_p = (YY_CHAR *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yyunput YY_PROTO(( YY_CHAR c, YY_CHAR *buf_ptr ));
void yyrestart YY_PROTO(( FILE *input_file ));
void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));

#define yy_new_buffer yy_create_buffer

#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif

YY_DECL
    {
    register yy_state_type yy_current_state;
    register YY_CHAR *yy_cp, *yy_bp;
    register int yy_act;




    if ( yy_init )
	{
	YY_USER_INIT;

	if ( ! yy_start )
	    yy_start = 1;	/* first start state */

	if ( ! yyin )
	    yyin = stdin;

	if ( ! yyout )
	    yyout = stdout;

	if ( yy_current_buffer )
	    yy_init_buffer( yy_current_buffer, yyin );
	else
	    yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_load_buffer_state();

	yy_init = 0;
	}

    while ( 1 )		/* loops until end-of-file is reached */
	{
	yy_cp = yy_c_buf_p;

	/* support of yytext */
	*yy_cp = yy_hold_char;

	/* yy_bp points to the position in yy_ch_buf of the start of the
	 * current run.
	 */
	yy_bp = yy_cp;

	yy_current_state = yy_start;
yy_match:
	do
	    {
	    register YY_CHAR yy_c = yy_ec[*yy_cp];
	    if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	    while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = yy_def[yy_current_state];
		if ( yy_current_state >= 270 )
		    yy_c = yy_meta[yy_c];
		}
	    yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	    ++yy_cp;
	    }
	while ( yy_current_state != 269 );
	yy_cp = yy_last_accepting_cpos;
	yy_current_state = yy_last_accepting_state;

yy_find_action:
	yy_act = yy_accept[yy_current_state];

	YY_DO_BEFORE_ACTION;
	YY_USER_ACTION;

do_action:	/* this label is used only to access EOF actions */


	switch ( yy_act )
	    {
	    case 0: /* must backtrack */
	    /* undo the effects of YY_DO_BEFORE_ACTION */
	    *yy_cp = yy_hold_char;
	    yy_cp = yy_last_accepting_cpos;
	    yy_current_state = yy_last_accepting_state;
	    goto yy_find_action;

case 1:
# line 6 "valspeak.l"
printf(" mean");
	YY_BREAK
case 2:
# line 7 "valspeak.l"
printf(" bitchin'est");
	YY_BREAK
case 3:
# line 8 "valspeak.l"
printf(" bod");
	YY_BREAK
case 4:
# line 9 "valspeak.l"
printf(" drag");
	YY_BREAK
case 5:
# line 10 "valspeak.l"
printf(" rod ");
	YY_BREAK
case 6:
# line 11 "valspeak.l"
printf(" grodie");
	YY_BREAK
case 7:
# line 12 "valspeak.l"
printf(" grodie to thuh max");
	YY_BREAK
case 8:
# line 13 "valspeak.l"
printf(" munchies");
	YY_BREAK
case 9:
# line 14 "valspeak.l"
printf(" chick");
	YY_BREAK
case 10:
# line 15 "valspeak.l"
printf(" bitchin'");
	YY_BREAK
case 11:
# line 16 "valspeak.l"
printf(" awesum");
	YY_BREAK
case 12:
# line 17 "valspeak.l"
printf(" grodie");
	YY_BREAK
case 13:
# line 18 "valspeak.l"
printf(" dude");
	YY_BREAK
case 14:
# line 19 "valspeak.l"
printf(" that chick ");
	YY_BREAK
case 15:
# line 20 "valspeak.l"
printf(" that chick.");
	YY_BREAK
case 16:
# line 21 "valspeak.l"
printf(" that dude ");
	YY_BREAK
case 17:
# line 22 "valspeak.l"
printf(" that dude.");
	YY_BREAK
case 18:
# line 24 "valspeak.l"
case 19:
# line 25 "valspeak.l"
case 20:
# line 26 "valspeak.l"
case 21:
# line 27 "valspeak.l"
case 22:
# line 28 "valspeak.l"
case 23:
# line 29 "valspeak.l"
case 24:
# line 30 "valspeak.l"
case 25:
# line 31 "valspeak.l"
case 26:
# line 32 "valspeak.l"
case 27:
# line 33 "valspeak.l"
case 28:
# line 33 "valspeak.l"
{
			ECHO;
			switch(rand() % 6)
			{
			case 0:
				printf("like, ya know, "); break;
			case 1:
				printf(""); break;
			case 2:
				printf("like wow! "); break;
			case 3:
				printf("ya know, like, "); break;
			case 4:
				printf(""); break;
			case 5:
				printf(""); break;
			}
		}
	YY_BREAK
case 29:
# line 51 "valspeak.l"
printf(" pad");
	YY_BREAK
case 30:
# line 52 "valspeak.l"
printf(" cool");
	YY_BREAK
case 31:
# line 53 "valspeak.l"
printf(" awesum");
	YY_BREAK
case 32:
# line 54 "valspeak.l"
printf(" blow");
	YY_BREAK
case 33:
# line 55 "valspeak.l"
printf(" nerd ");
	YY_BREAK
case 34:
# line 56 "valspeak.l"
{
			switch(rand() % 6)
			{
			case 0:
				printf(" if you're a Pisces "); break;
			case 1:
				printf(" if the moon is full "); break;
			case 2:
				printf(" if the vibes are right "); break;
			case 3:
				printf(" when you get the feeling "); break;
			case 4:
				printf(" maybe "); break;
			case 5:
				printf(" maybe "); break;
			}
		}
	YY_BREAK
case 35:
# line 73 "valspeak.l"
printf(" party");
	YY_BREAK
case 36:
# line 74 "valspeak.l"
printf(" flick");
	YY_BREAK
case 37:
# line 75 "valspeak.l"
printf(" tunes ");
	YY_BREAK
case 38:
# line 76 "valspeak.l"
printf(" keen");
	YY_BREAK
case 39:
# line 77 "valspeak.l"
printf(" class");
	YY_BREAK
case 40:
# line 78 "valspeak.l"
printf(" just no way");
	YY_BREAK
case 41:
# line 79 "valspeak.l"
printf(" guys");
	YY_BREAK
case 42:
# line 80 "valspeak.l"
printf(" totally");
	YY_BREAK
case 43:
# line 81 "valspeak.l"
printf(" freaky");
	YY_BREAK
case 44:
# line 82 "valspeak.l"
printf(" thuh ");
	YY_BREAK
case 45:
# line 83 "valspeak.l"
printf(" super");
	YY_BREAK
case 46:
# line 84 "valspeak.l"
printf(" want");
	YY_BREAK
case 47:
# line 85 "valspeak.l"
printf(" far out");
	YY_BREAK
case 48:
# line 86 "valspeak.l"
printf(" fer shure");
	YY_BREAK
case 49:
# line 87 "valspeak.l"
printf("Man, ");
	YY_BREAK
case 50:
# line 88 "valspeak.l"
printf("That dude ");
	YY_BREAK
case 51:
# line 89 "valspeak.l"
printf("I can dig");
	YY_BREAK
case 52:
# line 90 "valspeak.l"
printf("Like, no way,");
	YY_BREAK
case 53:
# line 91 "valspeak.l"
printf("Man");
	YY_BREAK
case 54:
# line 92 "valspeak.l"
printf("That fox ");
	YY_BREAK
case 55:
# line 93 "valspeak.l"
printf("Like, ya know, this");
	YY_BREAK
case 56:
# line 94 "valspeak.l"
printf("Like, there");
	YY_BREAK
case 57:
# line 95 "valspeak.l"
printf("Us guys ");
	YY_BREAK
case 58:
# line 96 "valspeak.l"
printf("Like,");
	YY_BREAK
case 59:
# line 97 "valspeak.l"
{
			switch(rand() % 6)
			{
			case 0:
				printf(", like, "); break;
			case 1:
				printf(", fer shure, "); break;
			case 2:
				printf(", like, wow, "); break;
			case 3:
				printf(", oh, baby, "); break;
			case 4:
				printf(", man, "); break;
			case 5:
				printf(", mostly, "); break;
			}
		}
	YY_BREAK
case 60:
# line 114 "valspeak.l"
{
			switch(rand() % 3)
			{
			case 0:
				printf("!  Gag me with a SPOOOOON!"); break;
			case 1:
				printf("!  Gag me with a pitchfork!"); break;
			case 2:
				printf("!  Oh, wow!");
			}
		}
	YY_BREAK
case 61:
# line 126 "valspeak.l"
printf("in'");
	YY_BREAK
case 62:
# line 127 "valspeak.l"
ECHO;
	YY_BREAK
case 63:
# line 128 "valspeak.l"
ECHO;
	YY_BREAK
case YY_STATE_EOF(INITIAL):
    yyterminate();

	    case YY_END_OF_BUFFER:
		{
		/* amount of text matched not including the EOB char */
		int yy_amount_of_matched_text = yy_cp - yytext - 1;

		/* undo the effects of YY_DO_BEFORE_ACTION */
		*yy_cp = yy_hold_char;

		/* note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the end-
		 * of-buffer state).  Contrast this with the test in yyinput().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
		    /* this was really a NUL */
		    {
		    yy_state_type yy_next_state;

		    yy_c_buf_p = yytext + yy_amount_of_matched_text;

		    yy_current_state = yy_get_previous_state();

		    /* okay, we're now positioned to make the
		     * NUL transition.  We couldn't have
		     * yy_get_previous_state() go ahead and do it
		     * for us because it doesn't know how to deal
		     * with the possibility of jamming (and we
		     * don't want to build jamming into it because
		     * then it will run more slowly)
		     */

		    yy_next_state = yy_try_NUL_trans( yy_current_state );

		    yy_bp = yytext + YY_MORE_ADJ;

		    if ( yy_next_state )
			{
			/* consume the NUL */
			yy_cp = ++yy_c_buf_p;
			yy_current_state = yy_next_state;
			goto yy_match;
			}

		    else
			{
			    yy_cp = yy_last_accepting_cpos;
			    yy_current_state = yy_last_accepting_state;
			goto yy_find_action;
			}
		    }

		else switch ( yy_get_next_buffer() )
		    {
		    case EOB_ACT_END_OF_FILE:
			{
			yy_did_buffer_switch_on_eof = 0;

			if ( yywrap() )
			    {
			    /* note: because we've taken care in
			     * yy_get_next_buffer() to have set up yytext,
			     * we can now set up yy_c_buf_p so that if some
			     * total hoser (like flex itself) wants
			     * to call the scanner after we return the
			     * YY_NULL, it'll still work - another YY_NULL
			     * will get returned.
			     */
			    yy_c_buf_p = yytext + YY_MORE_ADJ;

			    yy_act = YY_STATE_EOF((yy_start - 1) / 2);
			    goto do_action;
			    }

			else
			    {
			    if ( ! yy_did_buffer_switch_on_eof )
				YY_NEW_FILE;
			    }
			}
			break;

		    case EOB_ACT_CONTINUE_SCAN:
			yy_c_buf_p = yytext + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			yy_cp = yy_c_buf_p;
			yy_bp = yytext + YY_MORE_ADJ;
			goto yy_match;

		    case EOB_ACT_LAST_MATCH:
			yy_c_buf_p =
			    &yy_current_buffer->yy_ch_buf[yy_n_chars];

			yy_current_state = yy_get_previous_state();

			yy_cp = yy_c_buf_p;
			yy_bp = yytext + YY_MORE_ADJ;
			goto yy_find_action;
		    }
		break;
		}

	    default:
#ifdef FLEX_DEBUG
		printf( "action # %d\n", yy_act );
#endif
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	    }
	}
    }


/* yy_get_next_buffer - try to read in a new buffer
 *
 * synopsis
 *     int yy_get_next_buffer();
 *     
 * returns a code representing an action
 *     EOB_ACT_LAST_MATCH - 
 *     EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *     EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()

    {
    register YY_CHAR *dest = yy_current_buffer->yy_ch_buf;
    register YY_CHAR *source = yytext - 1; /* copy prev. char, too */
    register int number_to_move, i;
    int ret_val;

    if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
	YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

    /* try to read more data */

    /* first move last chars to start of buffer */
    number_to_move = yy_c_buf_p - yytext;

    for ( i = 0; i < number_to_move; ++i )
	*(dest++) = *(source++);

    if ( yy_current_buffer->yy_eof_status != EOF_NOT_SEEN )
	/* don't do the read, it's not guaranteed to return an EOF,
	 * just force an EOF
	 */
	yy_n_chars = 0;

    else
	{
	int num_to_read = yy_current_buffer->yy_buf_size - number_to_move - 1;

	if ( num_to_read > YY_READ_BUF_SIZE )
	    num_to_read = YY_READ_BUF_SIZE;

	else if ( num_to_read <= 0 )
	    YY_FATAL_ERROR( "fatal error - scanner input buffer overflow" );

	/* read in more data */
	YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
		  yy_n_chars, num_to_read );
	}

    if ( yy_n_chars == 0 )
	{
	if ( number_to_move == 1 )
	    {
	    ret_val = EOB_ACT_END_OF_FILE;
	    yy_current_buffer->yy_eof_status = EOF_DONE;
	    }

	else
	    {
	    ret_val = EOB_ACT_LAST_MATCH;
	    yy_current_buffer->yy_eof_status = EOF_PENDING;
	    }
	}

    else
	ret_val = EOB_ACT_CONTINUE_SCAN;

    yy_n_chars += number_to_move;
    yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
    yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

    /* yytext begins at the second character in yy_ch_buf; the first
     * character is the one which preceded it before reading in the latest
     * buffer; it needs to be kept around in case it's a newline, so
     * yy_get_previous_state() will have with '^' rules active
     */

    yytext = &yy_current_buffer->yy_ch_buf[1];

    return ( ret_val );
    }


/* yy_get_previous_state - get the state just before the EOB char was reached
 *
 * synopsis
 *     yy_state_type yy_get_previous_state();
 */

static yy_state_type yy_get_previous_state()

    {
    register yy_state_type yy_current_state;
    register YY_CHAR *yy_cp;

    yy_current_state = yy_start;

    for ( yy_cp = yytext + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
	{
	register YY_CHAR yy_c = (*yy_cp ? yy_ec[*yy_cp] : 1);
	if ( yy_accept[yy_current_state] )
	    {
	    yy_last_accepting_state = yy_current_state;
	    yy_last_accepting_cpos = yy_cp;
	    }
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
	    {
	    yy_current_state = yy_def[yy_current_state];
	    if ( yy_current_state >= 270 )
		yy_c = yy_meta[yy_c];
	    }
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	}

    return ( yy_current_state );
    }


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *     next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( register yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
register yy_state_type yy_current_state;
#endif

    {
    register int yy_is_jam;
    register YY_CHAR *yy_cp = yy_c_buf_p;

    register YY_CHAR yy_c = 1;
    if ( yy_accept[yy_current_state] )
	{
	yy_last_accepting_state = yy_current_state;
	yy_last_accepting_cpos = yy_cp;
	}
    while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
	{
	yy_current_state = yy_def[yy_current_state];
	if ( yy_current_state >= 270 )
	    yy_c = yy_meta[yy_c];
	}
    yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
    yy_is_jam = (yy_current_state == 269);

    return ( yy_is_jam ? 0 : yy_current_state );
    }


#ifdef YY_USE_PROTOS
static void yyunput( YY_CHAR c, register YY_CHAR *yy_bp )
#else
static void yyunput( c, yy_bp )
YY_CHAR c;
register YY_CHAR *yy_bp;
#endif

    {
    register YY_CHAR *yy_cp = yy_c_buf_p;

    /* undo effects of setting up yytext */
    *yy_cp = yy_hold_char;

    if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
	{ /* need to shift things up to make room */
	register int number_to_move = yy_n_chars + 2; /* +2 for EOB chars */
	register YY_CHAR *dest =
	    &yy_current_buffer->yy_ch_buf[yy_current_buffer->yy_buf_size + 2];
	register YY_CHAR *source =
	    &yy_current_buffer->yy_ch_buf[number_to_move];

	while ( source > yy_current_buffer->yy_ch_buf )
	    *--dest = *--source;

	yy_cp += dest - source;
	yy_bp += dest - source;
	yy_n_chars = yy_current_buffer->yy_buf_size;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
	    YY_FATAL_ERROR( "flex scanner push-back overflow" );
	}

    if ( yy_cp > yy_bp && yy_cp[-1] == '\n' )
	yy_cp[-2] = '\n';

    *--yy_cp = c;

    /* note: the formal parameter *must* be called "yy_bp" for this
     *       macro to now work correctly
     */
    YY_DO_BEFORE_ACTION; /* set up yytext again */
    }


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif

    {
    int c;
    YY_CHAR *yy_cp = yy_c_buf_p;

    *yy_cp = yy_hold_char;

    if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
	{
	/* yy_c_buf_p now points to the character we want to return.
	 * If this occurs *before* the EOB characters, then it's a
	 * valid NUL; if not, then we've hit the end of the buffer.
	 */
	if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
	    /* this was really a NUL */
	    *yy_c_buf_p = '\0';

	else
	    { /* need more input */
	    yytext = yy_c_buf_p;
	    ++yy_c_buf_p;

	    switch ( yy_get_next_buffer() )
		{
		case EOB_ACT_END_OF_FILE:
		    {
		    if ( yywrap() )
			{
			yy_c_buf_p = yytext + YY_MORE_ADJ;
			return ( EOF );
			}

		    YY_NEW_FILE;

#ifdef __cplusplus
		    return ( yyinput() );
#else
		    return ( input() );
#endif
		    }
		    break;

		case EOB_ACT_CONTINUE_SCAN:
		    yy_c_buf_p = yytext + YY_MORE_ADJ;
		    break;

		case EOB_ACT_LAST_MATCH:
#ifdef __cplusplus
		    YY_FATAL_ERROR( "unexpected last match in yyinput()" );
#else
		    YY_FATAL_ERROR( "unexpected last match in input()" );
#endif
		}
	    }
	}

    c = *yy_c_buf_p;
    yy_hold_char = *++yy_c_buf_p;

    return ( c );
    }


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif

    {
    yy_init_buffer( yy_current_buffer, input_file );
    yy_load_buffer_state();
    }


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif

    {
    if ( yy_current_buffer == new_buffer )
	return;

    if ( yy_current_buffer )
	{
	/* flush out information for old buffer */
	*yy_c_buf_p = yy_hold_char;
	yy_current_buffer->yy_buf_pos = yy_c_buf_p;
	yy_current_buffer->yy_n_chars = yy_n_chars;
	}

    yy_current_buffer = new_buffer;
    yy_load_buffer_state();

    /* we don't actually know whether we did this switch during
     * EOF (yywrap()) processing, but the only time this flag
     * is looked at is after yywrap() is called, so it's safe
     * to go ahead and always set it.
     */
    yy_did_buffer_switch_on_eof = 1;
    }


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif

    {
    yy_n_chars = yy_current_buffer->yy_n_chars;
    yytext = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
    yyin = yy_current_buffer->yy_input_file;
    yy_hold_char = *yy_c_buf_p;
    }


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif

    {
    YY_BUFFER_STATE b;

    b = (YY_BUFFER_STATE) malloc( sizeof( struct yy_buffer_state ) );

    if ( ! b )
	YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

    b->yy_buf_size = size;

    /* yy_ch_buf has to be 2 characters longer than the size given because
     * we need to put in 2 end-of-buffer characters.
     */
    b->yy_ch_buf = (YY_CHAR *) malloc( (unsigned) (b->yy_buf_size + 2) );

    if ( ! b->yy_ch_buf )
	YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

    yy_init_buffer( b, file );

    return ( b );
    }


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif

    {
    if ( b == yy_current_buffer )
	yy_current_buffer = (YY_BUFFER_STATE) 0;

    free( (char *) b->yy_ch_buf );
    free( (char *) b );
    }


#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif

    {
    b->yy_input_file = file;

    /* we put in the '\n' and start reading from [1] so that an
     * initial match-at-newline will be true.
     */

    b->yy_ch_buf[0] = '\n';
    b->yy_n_chars = 1;

    /* we always need two end-of-buffer characters.  The first causes
     * a transition to the end-of-buffer state.  The second causes
     * a jam in that state.
     */
    b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;
    b->yy_ch_buf[2] = YY_END_OF_BUFFER_CHAR;

    b->yy_buf_pos = &b->yy_ch_buf[1];

    b->yy_eof_status = EOF_NOT_SEEN;
    }
# line 128 "valspeak.l"


main()
{
	srand(getpid());
	yylex();
}
